/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-23 06:31:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberJoinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\t/* 도로명 주소 */\r\n");
      out.write("\t\tfunction goPopup(){ \r\n");
      out.write("\t\t\t//경로는 시스템에 맞게 수정하여 사용 \r\n");
      out.write("\t\t\t//호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrLinkUrl.do)를  \r\n");
      out.write("\t\t\t//호출하게 됩니다. \r\n");
      out.write("\t\t\tvar pop = window.open(\"popup/jusoPopup.jsp\",\"pop\",\"width=570, height=420, scrollbars=yes, resizable=yes\");  \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction jusoCallBack(roadFullAddr, roadAddrPart1, addrDetail, roadAddrPart2, engAddr, jibunAddr, zipNo, \r\n");
      out.write("\t\t\t\tadmCd, rnMgtSn, bdMgtSn , detBdNmList, bdNm, bdKdcd, siNm, sggNm, emdNm, liNm, rn, udrtYn, buldMnnm, \r\n");
      out.write("\t\t\t\tbuldSlno, mtYn, lnbrMnnm, lnbrSlno, emdNo){     // zipNo , roadAddrPart1 , roadAddrPart2 addrDetail \r\n");
      out.write("\t\t\t// 2017년 2월 제공항목이 추가되었습니다. 원하시는 항목을 추가하여 사용하시면 됩니다.    \r\n");
      out.write("\t\t\tdocument.joinForm.zipNo.value = zipNo;                 //우편번호\t\t\t\r\n");
      out.write("\t\t\tdocument.joinForm.roadAddrPart1.value = roadAddrPart1; //도로명주소(참고항목 제외)  \r\n");
      out.write("\t\t\tdocument.joinForm.roadAddrPart2.value = roadAddrPart2; //도로명주소 참고항목\r\n");
      out.write("\t\t\tdocument.joinForm.addrDetail.value = addrDetail;       //고객 입력 상세 주소\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\t\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>울타리 회원가입</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel= \"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/ultaryLogin.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!----해더 시작--------------------------------------------------------------------->\r\n");
      out.write("<!-- 시멘틱 태그 최대한 활용하기 -->\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t\t<a href='");
      out.print( request.getContextPath() );
      out.write("/views/main/main.jsp' target=\"_self\">\r\n");
      out.write("\t\t\t<img id=\"logo\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/logo.png\" width=\"120px\" height=\"90px\" /></a>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("<!----해더 끝--------------------------------------------------------------------->\r\n");
      out.write("<!-- nav 생략 -->\r\n");
      out.write("\r\n");
      out.write("<!----회원가입 기본 테이블 섹션  시작--------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"section_newMember\">\r\n");
      out.write("\t\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/insert.mem\" method=\"post\" id=\"joinForm\" name=\"joinForm\" onsubmit=\"return emalivalidate();\">\r\n");
      out.write("\t\t\t<div class=\"tableArea\">\r\n");
      out.write("\t\t\t\t<h1 align=\"center\">회 원 가 입</h1>\r\n");
      out.write("\t\t\t\t<hr width=50% color=\"white\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"align:middle;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"memberid\" name=\"memberid\" class=\"member\" maxlength=\"11\" required autofocus>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label id=\"idResult\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"memberid_check\"  style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/check.png\" width=\"15px\" height=\"15px\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"memberid_checked\" style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/checked.png\" width=\"15px\" height=\"15px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"membername\" name=\"membername\" class=\"member\" maxlength=\"11\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label id=\"nameResult\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"membername_check\"  style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/check.png\" width=\"15px\" height=\"15px\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"membername_checked\" style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/checked.png\" width=\"15px\" height=\"15px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>닉네임</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"nickname\" name=\"nickname\" class=\"member\" maxlength=\"11\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label id=\"nickResult\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"nickname_check\"  style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/check.png\" width=\"15px\" height=\"15px\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"nickname_checked\" style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/checked.png\" width=\"15px\" height=\"15px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>비밀번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=password name=\"password\" class=\"member\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label id=\"pwdResult1\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"password_check\"  style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/check.png\" width=\"15px\" height=\"15px\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"password_checked\" style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/checked.png\" width=\"15px\" height=\"15px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>비밀번호 재확인</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"passwordcheck\" name=\"passwordcheck\" class=\"member\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label id=\"pwdResult2\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"passwordcheck_check\"  style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/check.png\" width=\"15px\" height=\"15px\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"passwordcheck_checked\" style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/checked.png\" width=\"15px\" height=\"15px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>생년월일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select id=\"birth_year\" name=\"birthY\" class=\"member\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option disabled selected value=\"\">년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 for(int i=1950; i<2020;i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>");
      out.print( i );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>년\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"birth_month\" name=\"birthM\" class=\"member\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option class=\"member\" disabled selected value=\"\">월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01\">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03\">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04\">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05\">5</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06\">6</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07\">7</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08\">8</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09\">9</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>월\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"birth_day\" name=\"birthD\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option disabled selected value=\"\">일</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 for(int i=1;i<=31;i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(i<10){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>0");
      out.print( i );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>");
      out.print( i );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>일\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>성별</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"gender_F\" name=\"gender\" class=\"member\" value=\"F\" required checked><label>여자</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"gender_M\" name=\"gender\" class=\"member\" value=\"M\" required><label>남자</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>휴대전화번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"phone1\" name=\"phone1\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>019</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\t\t- <input type=\"text\" id=\"phone2\" name=\"phone2\" maxlength=\"4\" placeholder=\"1234\" style=\"width: 50px;\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t- <input type=\"text\" id=\"phone3\" name=\"phone3\" maxlength=\"4\" placeholder=\"5678\" style=\"width: 50px;\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>본인 확인 이메일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"email_1\" name=\"email_1\" class=\"member\" style=\"width: 100px;\" required>@<input type=\"text\" id=\"email_2\" name=\"email_2\" class=\"member\" style=\"width: 100px;\" disabled> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"selectEmail\" name=\"selectEmail\" class=\"member\" style=\"width: 100px; margin-right: 10px\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option Selected disabled value=\"\">::선택하세요::</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select><input type=\"button\" value=\"메일인증\" id=\"sendChkEmail\" onclick=\"sendMail();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label id=\"emailResult\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"emailResult_check\"  style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/check.png\" width=\"15px\" height=\"15px\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"emailResult_checked\" style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/checked.png\" width=\"15px\" height=\"15px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>인증 번호 확인</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"email_Confirm\" name=\"email_Confirm\" class=\"member\" placeholder=\"인증번호를 입력하세요.\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label id=\"emailChkResult\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"인증확인\" id=\"chkNum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"emailChkResult_check\"  style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/check.png\" width=\"15px\" height=\"15px\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"emailChkResult_checked\" style=\"display:none;\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/checked.png\" width=\"15px\" height=\"15px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("<!--도로명주소 API 적용하기 --------------------------------------------------------------------------->\t\r\n");
      out.write("<!-- \t\t\tdocument.joinForm.zipNo.value = zipNo;                 //1우편번호\t\t\t -->\r\n");
      out.write("<!-- \t\t\tdocument.joinForm.roadAddrPart1.value = roadAddrPart1; //2도로명주소(참고항목 제외)   -->\r\n");
      out.write("<!-- \t\t\tdocument.joinForm.roadAddrPart2.value = roadAddrPart2; //3도로명주소 참고항목 -->\r\n");
      out.write("<!-- \t\t\tdocument.joinForm.addrDetail.value = addrDetail;       //4고객 입력 상세 주소\t-->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>우편번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t<!-- 1우편번호-->\t\t<input type=\"text\" id=\"zipNo\" name=\"zipNo\" width=\"60px\" required />\r\n");
      out.write("\t\t\t<!-- 팝업버튼 -->\t\t<input type=\"button\" value=\"검색\" onclick=\"goPopup();\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>도로명주소</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t<!--2도로명주소--> \t\t<input type=\"text\" id=\"roadAddrPart1\" name=\"roadAddrPart1\" width=\"240px\" required /><br>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>상세주소</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t<!-- 3참고주소 -->\t    <input type=\"text\" id=\"roadAddrPart2\" name=\"roadAddrPart2\" width=\"115px\" required />\r\n");
      out.write("\t\t\t<!-- 4고객입력 상세주소 --><input type=\"text\" id=\"addrDetail\" name=\"addrDetail\" width=\"115px\" required /><br>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("<!--도로명주소 API 적용하기 --------------------------------------------------------------------------->\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>비밀번호 질문</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select id=\"pwquery\" name=\"pwquery\" class=\"member\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option Selected disabled value=\"\">::비밀번호 질문을 선택하세요::</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">기억에 남는 추억의 장소는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">자신의 인생 좌우명은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">자신의 보물 제1호는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"4\">유년시절 가장 생각나는 친구 이름은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"5\">인상 깊게 읽은 책 이름은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"6\">자신이 두번째로 존경하는 인물은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"7\">어릴적 별명은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"8\">다시 태어나면 되고 싶은 것은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"9\">내가 좋아하는 캐릭터는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">내가 좋아하는 색깔은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>비밀번호 답</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" id=\"pwqans\" name=\"pwqans\" class=\"member\" required></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<br> <label id=\"trustQ\">&nbsp;반려동물 위탁 요청을 받으시겠습니까?</label> \r\n");
      out.write("\t\t\t\t<input type=\"radio\" onclick=\"setDisplay1();\" id=\"trust_Y\" name=\"trust\" value=\"Y\"><label>네</label>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" onclick=\"setDisplay2();\" id=\"trust_N\" name=\"trust\" value=\"N\" checked><label>아니요</label><br> <br>\r\n");
      out.write("\r\n");
      out.write("<!----위탁 테이블 섹션  시작--------------------------------------------------------------------->\r\n");
      out.write("<!-- hide/show -->\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=newMember_animal style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t<h3>위 탁 환 경</h3>\r\n");
      out.write("\t\t\t\t\t<hr width=50% color=\"white\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"trustway\">돌봄방식</label>\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"trustmeans1\" name=\"turstmeans\" value=\"1\" ><label>위탁</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"trustmeans2\" name=\"turstmeans\" value=\"2\" ><label>방문</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"trustmeans3\" name=\"turstmeans\" value=\"3\" ><label>산책</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"trustmeans4\" name=\"turstmeans\" value=\"4\" ><label>전체가능</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"trustway\">돌봄조건</label>\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\" id=\"trust_con1\" name=\"trustfield\" value=\"픽업여부\" class=\"sittercon\"><label>픽업여부</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"trust_con2\" name=\"trustfield\" value=\"마당여부\" class=\"sittercon\"><label>마당여부</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"trust_con3\" name=\"trustfield\" value=\"산책\" class=\"sittercon\"><label>산책</label><br> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"trust_con4\" name=\"trustfield\" value=\"목욕\" class=\"sittercon\"><label>목욕</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"trust_con5\" name=\"trustfield\" value=\"온도\" class=\"sittercon\"><label>온도</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"trust_con6\" name=\"trustfield\" value=\"대형동물\" class=\"sittercon\"><label>대형동물</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"padding-right: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"\">위탁세부사항</label>\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"trustAdd\" placeholder=\"내용을 입력하세요.\" cols=\"36\" rows=\"3\" style=\"resize: none;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("<!-- hide/show -->\r\n");
      out.write("<!----위탁 테이블 섹션  끝--------------------------------------------------------------------->\t\r\n");
      out.write("\t\t\t<hr width=50% color=\"white\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<button type=submit id=\"loginBtn_normal\" class=\"loginBtn\" value=\"가입하기\" >가입하기</button>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</section>\r\n");
      out.write("<!---- 테이블 섹션  끝--------------------------------------------------------------------->\t\r\n");
      out.write("\r\n");
      out.write("<!---- 풋터 시작 --------------------------------------------------------------------->\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<table id=\"footer\">\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"footer_link\" onclick=\"goNotice();\">공지사항</div></td>\r\n");
      out.write("\t\t\t\t\t<td>|</td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"footer_link\" onclick=\"goUltaryLoginMain();\">로그인</div></td>\r\n");
      out.write("\t\t\t\t\t<td>|</td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"footer_link\" onclick=\"gofindId();\">아이디 찾기</div></td>\r\n");
      out.write("\t\t\t\t\t<td>|</td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"footer_link\" onclick=\"gofindPwd();\">비밀번호 찾기</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</footer>\r\n");
      out.write("<!---- 풋터 끝 --------------------------------------------------------------------->\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t/* 이메일 입력방식  */\r\n");
      out.write("\t$('#selectEmail').change(function() {\r\n");
      out.write("\t\t$(\"#selectEmail option:selected\").each(function() {\r\n");
      out.write("\t\t\tif ($(this).val() == '1') { //직접입력일 경우 \r\n");
      out.write("\t\t\t\t$(\"#email_2\").val(''); //값 초기화 \r\n");
      out.write("\t\t\t\t$(\"#email_2\").attr(\"disabled\", false); //활성화 \r\n");
      out.write("\t\t\t} else { //직접입력이 아닐경우 \r\n");
      out.write("\t\t\t\t$(\"#email_2\").val($(this).text()); //선택값 입력 \r\n");
      out.write("\t\t\t\t$(\"#email_2\").attr(\"disabled\", false); //비활성화 \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 위탁요청  show hide */\r\n");
      out.write("\tfunction setDisplay1(){\r\n");
      out.write("\t    if($('input:radio[id=trust_Y]').is(':checked')){\r\n");
      out.write("\t        $('#newMember_animal').show();\r\n");
      out.write("\t    }else{\r\n");
      out.write("\t        $('#newMember_animal').hide();\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction setDisplay2(){\r\n");
      out.write("\t    if($('input:radio[id=trust_N]').is(':checked')){\r\n");
      out.write("\t        $('#newMember_animal').hide();\r\n");
      out.write("\t    }else{\r\n");
      out.write("\t        $('#newMember_animal').show();\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/* 아이디 유효성 검사 ajax 중복불가*/\r\n");
      out.write("\tvar isidUsable = false; \t// 아이디 중복 시false, 사용가능시 true\r\n");
      out.write("\tvar isIdChecked = false;\t// 아이디 중복확인을 했는지 안했는지 검사\r\n");
      out.write("\tvar re1 =/^[a-zA-Z\\d]{4,11}$/; // 아이디 정규식\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#memberid\").on('change paste keyup', function(){\r\n");
      out.write("\t\tisIdChecked = false;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#memberid').change(function(){\r\n");
      out.write("\t\tvar userId = $('#memberid');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!re1.test(userId.val())){ //아이디 값이 아니거나, 아이디값이 3자보다 짧으면\r\n");
      out.write("\t\t\talert('아이디는 영문자와 숫자로 4글자 이상 11글자 이하로 입력하세요.');\r\n");
      out.write("\t\t\tuserId.focus();\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:'");
      out.print( request.getContextPath() );
      out.write("/idCheck.mem',\r\n");
      out.write("\t\t\t\tdata:{userId: userId.val()},\r\n");
      out.write("\t\t\t\tsuccess: function(data){ //data로 반환 받아옴\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data == \"success\"){\r\n");
      out.write("// \t\t\t\t\t\t$('#idResult').text('사용가능합니다.');\r\n");
      out.write("// \t\t\t\t\t\t$('#idResult').css({'color':'green', 'float':'right','display':'inline-block','padding-right':'50px'});\r\n");
      out.write("\t\t\t\t\t\tisidUsable = true;\r\n");
      out.write("\t\t\t\t\t\tisIdChecked= true;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif($('#memberid_check').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\t\t\t\t$('#memberid_check').show();\r\n");
      out.write("\t\t\t\t\t\t\t$('#memberid_checked').hide();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("// \t\t\t\t\t\t$('#idResult').text('사용 불가능 합니다.');\r\n");
      out.write("// \t\t\t\t\t\t$('#idResult').css({'color':'red', 'float':'right','display':'inline-block', 'padding-right':'50px'});\r\n");
      out.write("\t\t\t\t\t\tuserId.focus();\r\n");
      out.write("\t\t\t\t\t\tisidUsable = false;\r\n");
      out.write("\t\t\t\t\t\tisIdChecked= false;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \tif($('#memberid_checked').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\t \t\t$('#memberid_checked').show();\r\n");
      out.write("\t\t\t\t \t\t$('#memberid_check').hide();\r\n");
      out.write("\t\t\t\t\t \t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 이름 유효성 검사 ajax 중복불가 */\r\n");
      out.write("\t\r\n");
      out.write("\tvar isnameUsable = false; \t// 이름  false, 사용가능시 true\r\n");
      out.write("\tvar re2 = /^[가-힣]{2,}$/; // 이름 정규식\r\n");
      out.write("\t\r\n");
      out.write("\t$('#membername').change(function(){\r\n");
      out.write("\t\tvar membername = $('#membername');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!re2.test(membername.val())){\r\n");
      out.write("// \t\t\t$('#nameResult').text('사용불가합니다.');\r\n");
      out.write("// \t\t\t$('#nameResult').css({'color':'red', 'float':'right','display':'inline-block', 'padding-right':'50px'});\r\n");
      out.write("\t\t\talert('이름은 한글로 2자이상 입력하세요.');\r\n");
      out.write("\t\t\tisnameUsable = false;\r\n");
      out.write("\t\t\tmembername.focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#membername_checked').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t \t\t$('#membername_checked').show();\r\n");
      out.write("\t\t \t\t$('#membername_check').hide();\r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("// \t\t\t$('#nameResult').text('사용가능합니다.');\r\n");
      out.write("// \t\t\t$('#nameResult').css({'color':'green', 'float':'right','display':'inline-block','padding-right':'50px'});\r\n");
      out.write("\t\t\tisnameUsable = true;\r\n");
      out.write("\r\n");
      out.write("\t\t\tif($('#membername_check').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\t$('#membername_check').show();\r\n");
      out.write("\t\t\t\t$('#membername_checked').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 닉네임 유효성 검사 ajax 중복불가 */\t\t\r\n");
      out.write("\tvar isnickUsable = false; \t// 닉네임 중복 시false, 사용가능시 true\r\n");
      out.write("\tvar isnickChecked = false;\t// 닉네임 중복확인을 했는지 안했는지 검사\r\n");
      out.write("\tvar re3 = /^[가-힣a-zA-Z\\d]{2,}$/; // 닉네임 정규식 한글 2자이상\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#nickname\").on('change paste keyup', function(){\r\n");
      out.write("\t\tisnickChecked = false;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#nickname').change(function(){\r\n");
      out.write("\t\tvar userNick = $('#nickname');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!re3.test(userNick.val())){\r\n");
      out.write("\t\t\talert('닉네임은 영문 혹은 한글 2자리 이상이어야 합니다.');\r\n");
      out.write("// \t\t\t$('#nickResult').text('사용 불가능 합니다.');\r\n");
      out.write("// \t\t\t$('#nickResult').css({'color':'red', 'float':'right','display':'inline-block', 'padding-right':'50px'});\r\n");
      out.write("\t\t\tuserNick.focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#nickname_checked').css(\"display\")==\"none\"){ //반려\r\n");
      out.write("\t\t \t\t$('#nickname_checked').show();\r\n");
      out.write("\t\t \t\t$('#nickname_check').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:'");
      out.print( request.getContextPath() );
      out.write("/nickNameCheck.mem',\r\n");
      out.write("\t\t\t\tdata:{userNick: userNick.val()},\r\n");
      out.write("\t\t\t\tsuccess: function(data){ //data로 반환 받아옴\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data == \"success\"){\r\n");
      out.write("// \t\t\t\t\t\t$('#nickResult').text('사용가능합니다.');\r\n");
      out.write("// \t\t\t\t\t\t$('#nickResult').css({'color':'green', 'float':'right','display':'inline-block','padding-right':'50px'});\r\n");
      out.write("\t\t\t\t\t\tisnickUsable = true;\r\n");
      out.write("\t\t\t\t\t\tisnickChecked= true;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif($('#nickname_check').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\t\t \t\t$('#nickname_check').show();\r\n");
      out.write("\t\t\t\t\t \t\t$('#nickname_checked').hide();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("// \t\t\t\t\t\t$('#nickResult').text('사용 불가능 합니다.');\r\n");
      out.write("// \t\t\t\t\t\t$('#nickResult').css({'color':'red', 'float':'right','display':'inline-block', 'padding-right':'50px'});\r\n");
      out.write("\t\t\t\t\t\tuserNick.focus();\r\n");
      out.write("\t\t\t\t\t\tisnickUsable = false;\r\n");
      out.write("\t\t\t\t\t\tisnickChecked= false;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif($('#nickname_checked').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\t\t \t\t$('#nickname_checked').show();\r\n");
      out.write("\t\t\t\t\t \t\t$('#nickname_check').hide();\r\n");
      out.write("\t\t\t\t\t\t \t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 비밀번호 유효성 검사 ajax 중복불가 */\t\t\r\n");
      out.write("\tvar ispassUsable = false;\r\n");
      out.write("\tvar ispassChecked = false;\r\n");
      out.write("\tvar re4 = /^[a-zA-Z\\d]{7,11}$/; \r\n");
      out.write("\tvar password = $('#password');\r\n");
      out.write("\tvar password2 = $('#passwordcheck');\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#password\").on('change paste keyup', function(){\r\n");
      out.write("\t\tispassChecked = false;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#password').change(function(){ //패스워드 1만 정규식 체크 후 \r\n");
      out.write("\t\tif(!re4.test(password.val())){\r\n");
      out.write("// \t\t\t$('#pwdResult1').text('사용 불가능 합니다.');\r\n");
      out.write("// \t\t\t$('#pwdResult1').css({'color':'red', 'float':'right','display':'inline-block', 'padding-right':'50px'});\r\n");
      out.write("\t\t\talert('비밀번호는 영문 7~11자리 이어야 합니다.');\r\n");
      out.write("\t\t\tpassword.focus();\r\n");
      out.write("\t\t\tispassUsable = false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#password_checked').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t \t\t$('#password_checked').show();\r\n");
      out.write("\t\t \t\t$('#password_check').hide();\r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("// \t\t\t$('#pwdResult1').text('사용가능합니다.');\r\n");
      out.write("// \t\t\t$('#pwdResult1').css({'color':'green', 'float':'right','display':'inline-block','padding-right':'50px'});\r\n");
      out.write("\t\t\tispassUsable = true;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#password_check').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t \t\t$('#password_check').show();\r\n");
      out.write("\t\t \t\t$('#password_checked').hide();\r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//패스워드 1과 패스워트 2 동일한지 검사.\r\n");
      out.write("\t$('#passwordcheck').keyup(function(){\r\n");
      out.write("\t\tif(password.val() == password2.val()){\r\n");
      out.write("// \t\t\t$('#pwdResult2').text('사용가능합니다.');\r\n");
      out.write("// \t\t\t$('#pwdResult2').css({'color':'green', 'float':'right','display':'inline-block','padding-right':'50px'});\r\n");
      out.write("\t\t\tispassUsable = true;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#passwordcheck_check').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t \t\t$('#passwordcheck_check').show();\r\n");
      out.write("\t\t \t\t$('#passwordcheck_checked').hide();\r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("// \t\t\t$('#pwdResult2').text('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("// \t\t\t$('#pwdResult2').css({'color':'red', 'float':'right','display':'inline-block', 'padding-right':'50px'});\r\n");
      out.write("\t\t\tpassword2.focus();\r\n");
      out.write("\t\t\tispassUsable = false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#passwordcheck_checked').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t \t\t$('#passwordcheck_checked').show();\r\n");
      out.write("\t\t \t\t$('#passwordcheck_check').hide();\r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t/*이메일 중복 확인메일 발송  */ //emailResult\r\n");
      out.write("\tvar ismailUsable = false; \t// 이메일 중복 시false, 사용가능시 true\r\n");
      out.write("// \tvar ismailChecked = false;\t// 이메일 중복확인을 했는지 안했는지 검사\r\n");
      out.write("\t\r\n");
      out.write("\t$('#email_1,#email_2').on('paste keyup', function(){\r\n");
      out.write("\t\tismailChecked = false;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction sendMail(){\r\n");
      out.write("\t\tvar email_1 = $('#email_1'); \r\n");
      out.write("\t\tvar email_2 = $('#email_2'); \r\n");
      out.write("\t\tvar email = email_1.val() + '@' + email_2.val();\r\n");
      out.write("\t\tvar email_Confirm =$('#email_Confirm');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({  //이메일이 중복되는지 확인\r\n");
      out.write("\t\t\turl: '");
      out.print( request.getContextPath() );
      out.write("/email.mem',\r\n");
      out.write("\t\t\tdata: {email:email},\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(email_1.val() != \"\" && email_2.val() != \"\" && data == 'success'){ //중복아니라면 success =>인증메일 발송 가능\r\n");
      out.write("\t\t\t\t\t$.ajax({ //이메일 보내기\r\n");
      out.write("\t\t\t\t\t\turl: '");
      out.print( request.getContextPath() );
      out.write("/send.do',\r\n");
      out.write("\t\t\t\t\t\tdata: {email:email},\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(data1){\r\n");
      out.write("\r\n");
      out.write("// \t\t\t\t\t\t\t$('#emailResult').text('이메일 인증을 진행해주세요.');\r\n");
      out.write("\t\t\t\t\t\t\talert('입력하신 이메일로 인증메일이 발송되었습니다.');\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif($('#emailResult_check').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\t\t\t \t\t$('#emailResult_check').show();\r\n");
      out.write("\t\t\t\t\t\t \t\t$('#emailResult_checked').hide();\r\n");
      out.write("\t\t\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$('#chkNum').click(function(){ //인증확인 버튼을 눌렀을 때\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data1.trim() == $('#email_Confirm').val().trim()){ //인증번호와 사용자 입력이 일치하면\r\n");
      out.write("// \t\t\t\t\t\t\t\t\t$('#emailResult').text('이메일 인증에 성공하였습니다.');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tismailUsable = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tif($('#emailChkResult_check').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\t\t\t\t \t\t$('#emailChkResult_check').show();\r\n");
      out.write("\t\t\t\t\t\t\t \t\t$('#emailChkResult_checked').hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t }\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t} else{\r\n");
      out.write("// \t\t\t\t\t\t\t\t\t$('#emailResult').text('인증번호가 다릅니다.');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tismailUsable = false;\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert('인증번호가 일치하지 않습니다.');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif($('#emailChkResult_checked').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t$('#emailChkResult_checked').show();\r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t$('#emailChkResult_check').hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t} else{ //중복이라서 인증메일 발송 불가\r\n");
      out.write("\t\t\t\t\talert('중복된 이메일이거나 없는 이메일은 사용할 수 없습니다.');\r\n");
      out.write("\t\t\t\t\temail_1.select();\r\n");
      out.write("\t\t\t\t\tismailUsable = false;\r\n");
      out.write("// \t\t\t\t\t$('#emailResult').text('중복된 이메일은 사용할 수 없습니다.');\r\n");
      out.write("\t\t\t\t\tif($('#emailResult_checked').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\t \t\t$('#emailResult_checked').show();\r\n");
      out.write("\t\t\t\t \t\t$('#emailResult_check').hide();\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 이메일 인증번호 안적었는데 인증확인 먼저 눌렀을때 */\r\n");
      out.write("\t$('#chkNum').click(function(){\r\n");
      out.write("\t\tvar email_Confirm = $('#email_Confirm');\t\r\n");
      out.write("\t\r\n");
      out.write("\t\tif(email_Confirm.val() == \"\"){\r\n");
      out.write("\t\t\tif($('#emailChkResult_checked').css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\talert('인증번호를 입력하여 주시기 바랍니다.');\r\n");
      out.write("\t\t\t\temail_Confirm.focus();\r\n");
      out.write("\t\t \t\t$('#emailChkResult_checked').show();\r\n");
      out.write("\t\t \t\t$('#emailChkResult_check').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 메일인증 안하고 가입하기 눌렀을때 */\r\n");
      out.write("\tfunction emalivalidate(){\r\n");
      out.write("\t\tif(ismailUsable){\r\n");
      out.write("\t\t\treturn true; //가입\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert('메일인증을 진행해주세요.');\r\n");
      out.write("\t\t\temail_Confirm.focus();\r\n");
      out.write("\t\t\treturn false; //반려\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("//------------------------------------------------------------------------------------------------------------\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction goNotice(){ // 공지사항으로 이동\r\n");
      out.write("\t\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/#';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction goUltaryLoginMain(){ //로그인으로 이동\r\n");
      out.write("\t\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/views/main/ultaryLoginMain.jsp';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction gofindId(){ //아이디 찾기로 이동\r\n");
      out.write("\t\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/views/main/findMember/findIdForm.jsp';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction gofindPwd(){ // 비밀번호 찾기로 이동\r\n");
      out.write("\t\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/views/main/findMember/findPwdForm.jsp';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
