/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-22 12:19:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.myPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;
import java.util.ArrayList;

public final class memberUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

	Member loginUser = (Member)session.getAttribute("loginUser");
	ArrayList<Pet> loginPet = (ArrayList<Pet>)session.getAttribute("loginPet");
	ArrayList<Media> loginMedia = (ArrayList<Media>)session.getAttribute("loginMedia");
	String add = ((Member)session.getAttribute("loginUser")).getAddress();
	String[] addArr = add.split("/");
	String petkind = "";

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>내 정보 관리</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/myPage_css/memberUpdate.css\">\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-latest.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"script.js\"></script>\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("function goPopup(){\n");
      out.write("\t// 주소검색을 수행할 팝업 페이지를 호출합니다.\n");
      out.write("\t// 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrLinkUrl.do)를 호출하게 됩니다.\n");
      out.write("\tvar pop = window.open(\"addressUpdate_Popup.jsp\",\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\"); \n");
      out.write("\t\n");
      out.write("\t// 모바일 웹인 경우, 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrMobileLinkUrl.do)를 호출하게 됩니다.\n");
      out.write("    //var pop = window.open(\"/popup/jusoPopup.jsp\",\"pop\",\"scrollbars=yes, resizable=yes\"); \n");
      out.write("}\n");
      out.write("\n");
      out.write("function jusoCallBack(roadFullAddr, roadAddrPart1, addrDetail, roadAddrPart2, engAddr, jibunAddr, zipNo, \n");
      out.write("        admCd, rnMgtSn, bdMgtSn , detBdNmList, bdNm, bdKdcd, siNm, sggNm, emdNm, liNm, rn, udrtYn, buldMnnm, \n");
      out.write("        buldSlno, mtYn, lnbrMnnm, lnbrSlno, emdNo){\n");
      out.write("\t// 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\t\n");
      out.write("\t\t document.myForm.zipNo.value = zipNo;                 //우편번호         \n");
      out.write("         document.myForm.roadAddrPart1.value = roadAddrPart1; //도로명주소(참고항목 제외)  \n");
      out.write("         document.myForm.roadAddrPart2.value = roadAddrPart2; //도로명주소 참고항목\n");
      out.write("         document.myForm.addrDetail.value = addrDetail;       //고객 입력 상세 주소\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("// <a href=\"주소 입력\" onClick=\"window.open(this.href, '', 'width=400, height=430'); return false;\">하고픈 말</a>\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write(".text{font-family: 'Nanum Gothic Coding', monospace;}\n");
      out.write("\n");
      out.write("\t#mypage{\n");
      out.write("\t\twidth:900px;\n");
      out.write("\t\theight:1500px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#myForm{border: 1px solid hsla(197, 62%, 74%, 0.603); border-width: 20px; background: white; margin: 20px;}\n");
      out.write("\t#myForm2{border: 1px solid hsla(197, 62%, 74%, 0.603); border-width: 20px; background: white; margin: 20px;}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\ttable { margin-left: auto; margin-right: auto;\n");
      out.write(" \t\t    border-spacing: 20px;\n");
      out.write(" \t\t    border-collapse: separate;\n");
      out.write(" \t\t    \n");
      out.write("}\n");
      out.write("\t#newMember_animal{border: 1px solid hsla(197, 62%, 74%, 0.603); border-width: 5px; margin: 20px; margin-left: 150px; margin-right: 150px;\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t#petplus{\n");
      out.write("\t\twidth: 140px;\n");
      out.write("\t\tbox-shadow: 0px 1px 0px 0px #f0f7fa;\n");
      out.write("\t\tbackground:linear-gradient(to bottom, #33bdef 5%, #019ad2 100%);\n");
      out.write("\t\tbackground-color:#33bdef;\n");
      out.write("\t\tborder-radius:6px;\n");
      out.write("\t\tborder:1px solid #057fd0;\n");
      out.write("\t\tdisplay:inline-block;\n");
      out.write("\t\tcursor:pointer;\n");
      out.write("\t\tcolor:#ffffff;\n");
      out.write("\t\tfont-family:Arial;\n");
      out.write("\t\tfont-size:14px;\n");
      out.write("\t\tfont-weight:bold;\n");
      out.write("\t\tpadding:6px 24px;\n");
      out.write("\t\ttext-decoration:none;\n");
      out.write("\t\ttext-shadow:0px -1px 0px #5b6178;\n");
      out.write("\t\t}\n");
      out.write("\t\t#petplus:hover{\n");
      out.write("\t\tbackground:linear-gradient(to bottom, #019ad2 5%, #33bdef 100%);\n");
      out.write("\t\tbackground-color:#019ad2;\n");
      out.write("\t\t}\n");
      out.write("\t\t#petplus:active {\n");
      out.write("\t\tposition:relative;\n");
      out.write("\t\ttop:1px;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tinput:focus {\n");
      out.write("\t    outline: none;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t#retoch{\n");
      out.write("\t\twidth: 140px;\n");
      out.write("\t\tbox-shadow: 0px 1px 0px 0px #f0f7fa;\n");
      out.write("\t\tbackground:linear-gradient(to bottom, #33bdef 5%, #019ad2 100%);\n");
      out.write("\t\tbackground-color:#33bdef;\n");
      out.write("\t\tborder-radius:6px;\n");
      out.write("\t\tborder:1px solid #057fd0;\n");
      out.write("\t\tdisplay:inline-block;\n");
      out.write("\t\tcursor:pointer;\n");
      out.write("\t\tcolor:#ffffff;\n");
      out.write("\t\tfont-family:Arial;\n");
      out.write("\t\tfont-size:18px;\n");
      out.write("\t\tfont-weight:bold;\n");
      out.write("\t\tpadding:6px 24px;\n");
      out.write("\t\ttext-decoration:none;\n");
      out.write("\t\ttext-shadow:0px -1px 0px #5b6178;\n");
      out.write("\t\t}\n");
      out.write("\t\t#retoch:hover{\n");
      out.write("\t\tbackground:linear-gradient(to bottom, #019ad2 5%, #33bdef 100%);\n");
      out.write("\t\tbackground-color:#019ad2;\n");
      out.write("\t\t}\n");
      out.write("\t\t#retoch:active {\n");
      out.write("\t\tposition:relative;\n");
      out.write("\t\ttop:1px;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tinput:focus {\n");
      out.write("\t    outline: none;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tinput:focus {\n");
      out.write("\t    outline: none;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t#retoch2{\n");
      out.write("\t\twidth: 140px;\n");
      out.write("\t\tbox-shadow: 0px 1px 0px 0px #f0f7fa;\n");
      out.write("\t\tbackground:linear-gradient(to bottom, #33bdef 5%, #019ad2 100%);\n");
      out.write("\t\tbackground-color:#33bdef;\n");
      out.write("\t\tborder-radius:6px;\n");
      out.write("\t\tborder:1px solid #057fd0;\n");
      out.write("\t\tdisplay:inline-block;\n");
      out.write("\t\tcursor:pointer;\n");
      out.write("\t\tcolor:#ffffff;\n");
      out.write("\t\tfont-family:Arial;\n");
      out.write("\t\tfont-size:18px;\n");
      out.write("\t\tfont-weight:bold;\n");
      out.write("\t\tpadding:6px 24px;\n");
      out.write("\t\ttext-decoration:none;\n");
      out.write("\t\ttext-shadow:0px -1px 0px #5b6178;\n");
      out.write("\t\t}\n");
      out.write("\t\t#retoch2:hover{\n");
      out.write("\t\tbackground:linear-gradient(to bottom, #019ad2 5%, #33bdef 100%);\n");
      out.write("\t\tbackground-color:#019ad2;\n");
      out.write("\t\t}\n");
      out.write("\t\t#retoch2:active {\n");
      out.write("\t\tposition:relative;\n");
      out.write("\t\ttop:1px;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tinput:focus {\n");
      out.write("\t    outline: none;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\tth{background: hsla(197, 62%, 74%, 0.603); width: 120px; text-align: center;}\n");
      out.write("\th2{background: gainsboro; width: 200px;}\n");
      out.write("\tu{font_underlinecolor: gainsboro;}\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"all\">\n");
      out.write("\t\t<div id=\"all-wrap\">\n");
      out.write("\t\t\t<header>\n");
      out.write("\t\t\t\t<div id=\"header-top\">\n");
      out.write("\t\t\t\t\t<img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/알림.png\">\n");
      out.write("\t\t\t\t\t<img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/메신저.png\">\n");
      out.write("\t\t\t\t\t<div id=\"header-topR\">\n");
      out.write("\t\t\t\t\t\t<div id=\"nick\">");
      out.print( loginUser.getNickname() );
      out.write("</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"nim\">님</div>\n");
      out.write("\t\t\t\t\t\t<button id=\"logout\" class=\"top-right\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me'\">로그아웃</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"header-bottom\">\n");
      out.write("\t\t\t\t\t<img id=\"logoimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/logo.png\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</header>\n");
      out.write("\t\t\t<nav>\n");
      out.write("\t\t\t\t<div id='cssmenu'>\n");
      out.write("\t\t\t\t\t <ul>\n");
      out.write("                  <li>\n");
      out.write("                     <a href='#'>내울타리</a>\n");
      out.write("                     <ul id=\"menu1\">\n");
      out.write("                        <li><a href='#'>타임라인</a></li>\n");
      out.write("                        <li><a href='#'>게시글작성</a></li>\n");
      out.write("                        <li><a href='#'>관심회원</a></li>\n");
      out.write("                        <li><a href='#'>게시글 즐겨찾기</a></li>\n");
      out.write("                        <li><a href='#'>내 위탁환경</a></li>\n");
      out.write("                     </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li>\n");
      out.write("                     <a href='#'>커뮤니티</a>\n");
      out.write("                     <ul id=\"menu2\">\n");
      out.write("                        <li><a href='#'>공지사항</a></li>\n");
      out.write("                        <li><a href='#'>모아보기</a></li>\n");
      out.write("                        <li><a href='#'>펫일상</a></li>\n");
      out.write("                        <li><a href='#'>펫지식</a></li>\n");
      out.write("                        <li><a href='#'>펫리뷰</a></li>\n");
      out.write("                        <li><a href='#'>펫분양</a></li>\n");
      out.write("                     </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li><a href='#'>위탁매칭</a>\n");
      out.write("                     <ul id=\"menu3\">\n");
      out.write("                        <li><a href='#'>위탁검색</a></li>\n");
      out.write("                        <li><a href='#'>의뢰 관리</a></li>\n");
      out.write("                        <li><a href='#'>내가 남긴 리뷰</a></li>\n");
      out.write("                     </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class='active'><a href='#'>마이페이지</a>\n");
      out.write("                     <ul id=\"menu4\">\n");
      out.write("                        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myPage/memberUpdate.jsp\">내 정보 관리</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myPage/pwdUpdate.jsp\">비밀번호 변경</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myPage/memberDelete.jsp\">회원 탈퇴</a></li>\n");
      out.write("                     </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li><a href='#'>고객센터</a>\n");
      out.write("                     <ul id=\"menu5\">\n");
      out.write("                        <li><a href='#'>공지 사항</a></li>\n");
      out.write("                        <li><a href='#'>자주하는 질문</a></li>\n");
      out.write("                        <li><a href='#'>1:1 문의</a></li>\n");
      out.write("                     </ul>\n");
      out.write("                  </li>\n");
      out.write("               </ul>\n");
      out.write("            </div>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t\t<div id=\"asidesection\">\n");
      out.write("\t\t\t\t<aside>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li>내 정보 관리</li>\n");
      out.write("\t\t\t\t\t\t<li>비밀번호 변경</li>\n");
      out.write("\t\t\t\t\t\t<li>회원 탈퇴</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</aside>\n");
      out.write("\t\t\t\t<section>\n");
      out.write("\t\n");
      out.write("\t<center><h1><u>내 정보 관리</u></h1></center>\n");
      out.write("\t<hr width=50% color=\"white\">\n");
      out.write("\t<div id=\"mypage\">\n");
      out.write("\t<form id=\"myForm\" name = \"myForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/update.mem\" method=\"post\">\n");
      out.write("\t<center><h2>내 정보</h2></center>\n");
      out.write("\t<table>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>닉네임</th>\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"nickname\" id=\"nickname\" placeholder=\"닉네임을 입력하세요\" value=\"");
      out.print( loginUser.getNickname() );
      out.write("\"><button>중복체크</button></td>\n");
      out.write("\t\t\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>이름 </th>\n");
      out.write("\t\t\t<td>");
      out.print( loginUser.getMemberName() );
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>아이디</th>\n");
      out.write("\t\t\t<td>");
      out.print( loginUser.getMemberId() );
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>생년월일</th>\n");
      out.write("\t\t\t<td>");
      out.print( loginUser.getBirth() );
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>성별</th>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t");
      out.print( loginUser.getGender() );
      out.write("\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t<th>E-mail</th>\n");
      out.write("\t\t\t<td>");
      out.print( loginUser.getEmail() );
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>Phone</th>\n");
      out.write("\t\t\t<td><input name=\"phone\" id=\"phone\" value=\"");
      out.print( loginUser.getPhone() );
      out.write("\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("                     <th>우편번호</th>\n");
      out.write("                     <td>\n");
      out.write("         <!-- 1우편번호-->      <input type=\"text\" id=\"zipNo\" name=\"zipNo\" width=\"60px\" value=\"");
      out.print( addArr[0] );
      out.write("\"/>\n");
      out.write("        \t\t\t\n");
      out.write("       \t\t\t\t\n");
      out.write("         <!-- 팝업버튼 -->      <input type=\"button\" value=\"검색\" onclick=\"goPopup();\">\n");
      out.write("                     </td>\n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                     <th>도로명주소</th>\n");
      out.write("                     <td>\n");
      out.write("         <!--2도로명주소-->       <input type=\"text\" id=\"roadAddrPart1\" name=\"roadAddrPart1\" width=\"240px\" value=\"");
      out.print( addArr[1] );
      out.write("\"/><br>\n");
      out.write("         \t\t\t");
      out.write("\n");
      out.write("                     </td>\n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                     <th>상세주소</th>\n");
      out.write("                     <td>\n");
      out.write("         <!-- 3참고주소 -->       <input type=\"text\" id=\"roadAddrPart2\" name=\"roadAddrPart2\" width=\"115px\" value=\"");
      out.print( addArr[2] );
      out.write("\"/>\n");
      out.write("         \t\t\t");
      out.write("\n");
      out.write("         <!-- 4고객입력 상세주소 --><input type=\"text\" id=\"addrDetail\" name=\"addrDetail\" width=\"115px\" value=\"");
      out.print( addArr[3] );
      out.write("\"/><br>\n");
      out.write("         \t\t\t");
      out.write("\n");
      out.write("                     </td>\n");
      out.write("                  </tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>비밀번호 질문</th>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<select id=\"pwquery\" name=\"pwquery\" class=\"member\">\n");
      out.write("\t\t\t\t\t<option>비밀번호 질문</option>\n");
      out.write("\t\t\t\t\t<option value=\"1\">기억에 남는 추억의 장소는?</option>\n");
      out.write("\t\t\t\t\t<option value=\"2\">자신의 인생 좌우명은?</option>\n");
      out.write("\t\t\t\t\t<option value=\"3\">자신의 보물 제1호는?</option>\n");
      out.write("\t\t\t\t\t<option value=\"4\">유년시절 가장 생각나는 친구 이름은?</option>\n");
      out.write("\t\t\t\t\t<option value=\"5\">인상 깊게 읽은 책 이름은?</option>\n");
      out.write("\t\t\t\t\t<option value=\"6\">자신이 두번째로 존경하는 인물은?</option>\n");
      out.write("\t\t\t\t\t<option value=\"7\">어릴적 별명은?</option>\n");
      out.write("\t\t\t\t\t<option value=\"8\">다시 태어나면 되고 싶은 것은?</option>\n");
      out.write("\t\t\t\t\t<option value=\"9\">내가 좋아하는 캐릭터는?</option>\n");
      out.write("\t\t\t\t\t<option value=\"10\">내가 좋아하는 색깔은?</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<th>비밀번호 답</th>\n");
      out.write("\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"pwqans\" name=\"pwqans\"class=\"member\" value=\"");
      out.print( loginUser.getPwqAns() );
      out.write("\">\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>위탁여부</th>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<input\n");
      out.write("\t\t\t\t\ttype=\"radio\" onclick=\"setDisplay1();\" id=\"trust_Y\" name=\"trust\"\n");
      out.write("\t\t\t\t\tvalue=\"Y\"><label>네</label> <input type=\"radio\"\n");
      out.write("\t\t\t\t\tonclick=\"setDisplay2();\" id=\"trust_N\" name=\"trust\" value=\"N\"\n");
      out.write("\t\t\t\t\tchecked><label>아니요</label>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<script>\n");
      out.write("\tfunction setDisplay1(){\n");
      out.write("\t    if($('input:radio[id=trust_Y]').is(':checked')){\n");
      out.write("\t        $('#newMember_animal').show();\n");
      out.write("\t    }else{\n");
      out.write("\t        $('#newMember_animal').hide();\n");
      out.write("\t    }\n");
      out.write("\t}\n");
      out.write("\tfunction setDisplay2(){\n");
      out.write("\t    if($('input:radio[id=trust_N]').is(':checked')){\n");
      out.write("\t        $('#newMember_animal').hide();\n");
      out.write("\t    }else{\n");
      out.write("\t        $('#newMember_animal').show();\n");
      out.write("\t    }\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("\t$(function(){\n");
      out.write("\t\tif(");
      out.print( loginUser.getTrust() );
      out.write("== \"Y\"){\n");
      out.write("\t\t\t$('#trust_Y').attr('checked','checked');\n");
      out.write("\t\t} else if(");
      out.print( loginUser.getTrust() );
      out.write("== \"\"){\n");
      out.write("\t\t\t$('#trust_N').attr('checked','checked');\n");
      out.write("</script>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<div id=newMember_animal style=\"display: none;\">\t\n");
      out.write("\t\t<table>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>\n");
      out.write("\t\t\t\t<label class=\"trustway\">돌봄방식</label>\n");
      out.write("\t\t\t</th>\n");
      out.write("\t\t\t<td>\t\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"trustmeans1\" name=\"trustmeans\" value=\"1\" ><label>위탁</label>\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"trustmeans2\" name=\"trustmeans\" value=\"2\" ><label>방문</label>\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"trustmeans3\" name=\"trustmeans\" value=\"3\" ><label>산책</label>\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"trustmeans4\" name=\"trustmeans\" value=\"4\" ><label>전체가능</label>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("<script>\n");
      out.write("\t$(function(){\n");
      out.write("\t\tif(");
      out.print( loginUser.getTrustmeans() );
      out.write("== \"1\"){\n");
      out.write("\t\t\t$('#trustmeans1').attr('checked','checked');\n");
      out.write("\t\t} else if(");
      out.print( loginUser.getTrustmeans() );
      out.write("== \"2\"){\n");
      out.write("\t\t\t$('#trustmeans2').attr('checked','checked');\n");
      out.write("\t\t} else if(");
      out.print( loginUser.getTrustmeans() );
      out.write("== \"3\") {\n");
      out.write("\t\t\t$('#trustmeans3').attr('checked','checked');\n");
      out.write("\t\t} else if(");
      out.print( loginUser.getTrustmeans() );
      out.write("== \"4\") {\n");
      out.write("\t\t\t$('#trustmeans4').attr('checked','checked');\n");
      out.write("\t\t} \t\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>돌봄조건</th>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"trustfield\" value=\"픽업\" id=\"dolbombom\" ");
      out.print( "trustfield[0]" );
      out.write("> <label>픽업여부</label>\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"trustfield\" value=\"미당\" id=\"dolbombom\" ");
      out.print( "trustfield[1]" );
      out.write("> <label>마당여부</label>\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"trustfield\" value=\"야외\" id=\"dolbombom\" ");
      out.print( "trustfield[2]" );
      out.write("> <label>야외산책</label><br>\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"trustfield\" value=\"노령\" id=\"dolbombom\" ");
      out.print( "trustfield[3]" );
      out.write("> <label>노령여부</label>\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"trustfield\" value=\"대형\" id=\"dolbombom\" ");
      out.print( "trustfield[4]" );
      out.write("> <label>대형동물</label>\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"trustfield\" value=\"목욕\" id=\"dolbombom\" ");
      out.print( "trustfield[5]" );
      out.write("> <label>목욕가능</label>\t\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th style=\"padding-right: 20px;\"><label class=\"\">위탁 추가 사항</th>\n");
      out.write("\t\t\t<td><textarea name=\"trustAdd\" placeholder=\"추가사항을 입력해주세요\"\n");
      out.write("\t\t\t\t\t\t\t\t\tcols=\"36\" rows=\"3\" style=\"resize: none;\" ");
      out.print( loginUser.getTrustAdd() );
      out.write("></textarea></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t</div>\n");
      out.write("\t</table>\n");
      out.write("\t</div>\n");
      out.write("\t\t<center><input type=\"submit\" id=\"retoch2\" value=\"수정저장\" style='cursor:pointer;'></center><br>\n");
      out.write("\t</form>\n");
      out.write("\t\n");
      out.write("\t\t<center><h2>반려동물 정보</h2></center>\n");
      out.write("\t<!-- 여기부터 반려동물 정보칸 -->\n");
      out.write("\t\t<div id=\"petdiv\">\n");
      out.write("\t\t");
 for(int i=0;i<loginPet.size();i++){ 
			Pet p = loginPet.get(i);
			switch(p.getPetKind()){
			case '1': petkind="강아지"; break;
			case '2':	petkind="고양이"; break;
			case '3':	petkind="설치류"; break;
			case '4':	petkind="파충류"; break;
			case '5':	petkind="조류"; break;
			case '6':	petkind="어류"; break;
			case '7':	petkind="기타"; break;
			} 
      out.write("\n");
      out.write("\t\t\t");
 for(int j=0;j<loginMedia.size();j++){
				Media m = loginMedia.get(j); 
      out.write("\n");
      out.write("\t\t\t\t");
 if(p.getPetNum() == m.getPetNum()){ 
      out.write("\n");
      out.write("\t\t\t<table class=\"petone\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th>프로필  사진</th>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t<img src='");
      out.print( request.getContextPath() );
      out.write("/uploadFiles/");
      out.print( m.getWebName() );
      out.write("' border='0' class=\"fileInput\" id=\"basicImg\" width=\"200px\" height=\"126px\" style='cursor:pointer;'>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th>반려동물 이름</th>\n");
      out.write("\t\t\t\t\t<td>");
      out.print( p.getPetName() );
      out.write("</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th>반려동물 종류</th>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t");
      out.print( petkind );
      out.write("\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th>성별</th>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t");
      out.print( p.getPetGender() );
      out.write("\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th>나이</th>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t");
      out.print( p.getPetage() );
      out.write("\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t");
 } 
      out.write('\n');
      out.write('	');
      out.write('	');
 } 
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<center><input type=\"button\" id=\"petplus\" style=\"cursor:pointer;\" value=\"반려동물 변경\"></center>\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\t$('#petplus').click(function(){\n");
      out.write("\t\t\t\twindow.open('");
      out.print( request.getContextPath());
      out.write("/views/myPage/petList.jsp', 'pop', 'width=950, height=650');\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\t</div>\n");
      out.write("\t\t\t\t</section>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<footer>from.hoseong</footer>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
