/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-23 10:48:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.myUltary;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import member.model.vo.*;
import post.model.vo.*;
import member.model.vo.*;

public final class OtherultaryMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/myUltary/chat.jsp", Long.valueOf(1587544472405L));
    _jspx_dependants.put("/views/myUltary/othernavaside.jsp", Long.valueOf(1587544472612L));
    _jspx_dependants.put("/views/myUltary/OtherUltaryheader.jsp", Long.valueOf(1587544472199L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_packages.add("post.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Member loginUser = (Member)session.getAttribute("loginUser");
	String nickname = (String)request.getAttribute("nickname");
	ArrayList<Post> plist = (ArrayList<Post>)request.getAttribute("plist");
	ArrayList<PostComment> pclist = (ArrayList<PostComment>)request.getAttribute("pclist");
	ArrayList<Media> mlist = (ArrayList<Media>)request.getAttribute("mlist");
	ArrayList<CAns> calist = (ArrayList<CAns>)request.getAttribute("calist");
	ArrayList<Media> proList = (ArrayList<Media>)request.getAttribute("proList");
	ArrayList<MarkPost> mpList = (ArrayList<MarkPost>)request.getAttribute("mpList");
	Boolean markbl = (Boolean)request.getAttribute("markbl");
	int markscore = (int)request.getAttribute("markscore");
	String proimgroute = "";
	for(int i=0;i<mlist.size();i++){
		Media m = mlist.get(i);
		if(m.getMediaUse() == 1){
			proimgroute = m.getWebName();
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>");
      out.print( nickname );
      out.write("의 울타리</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/myUltary/otherultaryMain.css\">\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tansbull = true;\r\n");
      out.write("\t\tansempty = true;\r\n");
      out.write("\t\tcNumber = \"\"; // 댓글 번호\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/myUltary/chat.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"chatdiv\">\r\n");
      out.write("\t\t<div id=\"chatdivleft\">\r\n");
      out.write("\t\t\t<div id=\"chatdivleft1\">\r\n");
      out.write("\t\t\t\t<img id=\"individualtalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/갠톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"chatdivleft2\">\r\n");
      out.write("\t\t\t\t<img id=\"grouptalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/단체톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"chatdivright\">\r\n");
      out.write("\t\t\t<div id=\"chattitle\">울타리 톡</div>\r\n");
      out.write("\t\t\t<div id=\"chatsearch\">\r\n");
      out.write("\t\t\t\t<div id=\"chatsearchdiv\">\r\n");
      out.write("\t\t\t\t\t<img id=\"chatsearchimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/검색.png\">\r\n");
      out.write("\t\t\t\t\t<input id=\"chatsearchtext\" type=\"search\" placeholder=\"검색할 회원이나 채팅방을 입력해주세요.\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('#chatdiv').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('#chatdiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('#chatdiv').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#chatbtn').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div id=\"all\">\r\n");
      out.write("\t\t<div id=\"all-wrap\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/myUltary/myUltaryheader.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"alert-wrap\">\r\n");
      out.write("\t\t\t<div class=\"alert\">\r\n");
      out.write("\t\t\t\t<div id=\"alerttitle\">전체알림</div>\r\n");
      out.write("\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"alertspace\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('.alert').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('.alert').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('.alert').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#alertbuttondiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t<div id=\"header-top\">\r\n");
      out.write("\t\t\t<div id=\"chatbtn\"><img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/메신저.png\"></div>\r\n");
      out.write("\t\t\t<div id=\"alertbuttondiv\"><img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/알림.png\"></div>\r\n");
      out.write("\t\t\t<a href='");
      out.print( request.getContextPath() );
      out.write("/views/main/main.jsp'><img id=\"logimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/logo.png\"></a>\r\n");
      out.write("\t\t\t<div id=\"header-topR\">\r\n");
      out.write("\t\t\t\t<div id=\"nick\">");
      out.print( loginUser.getNickname() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t<div id=\"nim\">님</div>\r\n");
      out.write("\t\t\t\t<button id=\"logout\" class=\"top-right\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"header-bottom\">\r\n");
      out.write("\t\t\t<img id=\"backimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/1.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"proimgdiv\">\r\n");
      out.write("\t\t\t\t<div id=\"promaindiv\">\r\n");
      out.write("\t\t\t\t\t<img style=\"width: 100%; height: 100%\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/사진변경.png\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 if(proimgroute != ""){ 
      out.write("\r\n");
      out.write("\t\t\t\t<img id=\"proimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/uploadFiles/");
      out.print( proimgroute );
      out.write("\">\r\n");
      out.write("\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<img id=\"proimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"tlhostdiv\">\r\n");
      out.write("\t\t<div id=\"tlhost\">");
      out.print( nickname );
      out.write("</div>\r\n");
      out.write("\t\t<div id=\"tlmark\"><div id=\"tlmark1\">");
      out.print( markscore );
      out.write(" Follow!!</div></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#tlmark').click(function(){\r\n");
      out.write("\t\t\tvar markmem = \"");
      out.print( nickname );
      out.write("\";\r\n");
      out.write("\t\t\tvar memberid = \"");
      out.print( loginUser.getMemberId() );
      out.write("\";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: 'markmember.mark',\r\n");
      out.write("\t\t\t\tdata: {markmem:markmem, memberid:memberid},\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t");
 if(markbl){ 
      out.write("\r\n");
      out.write("\t\t$('#tlmark1').css(\"background\", \"gold\");\r\n");
      out.write("\t\t$('#tlmark1').mouseover(function(){\r\n");
      out.write("\t\t\t$('#tlmark1').css(\"background\", \"crimson\");\r\n");
      out.write("\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\t$('#tlmark1').css(\"background\", \"gold\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t$('#tlmark1').css(\"background\", \"crimson\");\r\n");
      out.write("\t\t$('#tlmark1').mouseover(function(){\r\n");
      out.write("\t\t\t$('#tlmark1').css(\"background\", \"gold\");\r\n");
      out.write("\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\t$('#tlmark1').css(\"background\", \"crimson\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/myUltary/navaside.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<div id='cssmenu'>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class='active'>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print( request.getContextPath() );
      out.write("/post.tl\">내울타리</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"menu1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print( request.getContextPath() );
      out.write("/post.tl\">타임라인</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myUltary/postWrite.jsp\">게시글작성</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/markmember.mem\">관심회원</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myUltary/markPost.jsp\">게시글 즐겨찾기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myUltary/trustEvm.jsp\">내 위탁환경</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href='#'>커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"menu2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>모아보기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>펫일상</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>펫지식</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>펫리뷰</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>펫분양</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href='#'>위탁매칭</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"menu3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>위탁검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>의뢰 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>내가 남긴 리뷰</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href='#'>마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"menu4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>내 정보 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>비밀번호변경</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>회원 탈퇴</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href='#'>고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"menu5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>공지 사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>자주하는 질문</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>1:1 문의</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"topBtn\">\r\n");
      out.write("\t\t\t\t<a href=\"#all\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/image/top버튼.png\" style=\"width:80%;height:80%\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<section>\r\n");
      out.write("\t\t\t\t<div class=\"sectiondiv\">\r\n");
      out.write("\t\t\t\t");
 if(plist.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t\t<h1>조회할 게시물이 없음</h1>\r\n");
      out.write("\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 for(int i = plist.size()-1; i >= 0; i--) { 
						Post p = plist.get(i);
						String category = "";
						switch(p.getCategorynum()){
						case 2 : category = "펫일상"; break;
						case 3 : category = "펫지식"; break;
						case 4 : category = "펫리뷰"; break;
						case 5 : category = "펫분양"; break;
						}
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"content1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"writer\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sectionimg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(proimgroute != ""){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"sectionpic\" src=\"");
      out.print( request.getContextPath() );
      out.write("/uploadFiles/");
      out.print( proimgroute );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"sectionpic\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sectionNick\">");
      out.print( nickname );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contentTitle\">");
      out.print( p.getPostTitle() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"writerR\">게시일 | ");
      out.print( p.getPostDate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 ArrayList<Media> imgList = new ArrayList<Media>();
							for(int j=0;j<mlist.size();j++) { 
								Media m = mlist.get(j); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(m.getPostNum() == p.getPostNum()) {
									imgList.add(m); 
								}
							}
									if(!imgList.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"slide\" id=\"slide");
      out.print( i );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t      <div id=\"back");
      out.print( i );
      out.write("\" class=\"slideBtn\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/image/왼쪽 화살표.png\" alt=\"\" width=\"50\"></div>\r\n");
      out.write("\t\t\t\t\t\t      <ul>\r\n");
      out.write("\t\t\t\t\t\t      ");
 for(int z=0;z<imgList.size();z++){
						      	Media real = imgList.get(z); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t        <li><img src=\"");
      out.print( request.getContextPath() );
      out.write("/uploadFiles/");
      out.print( real.getWebName() );
      out.write("\" alt=\"\" width=\"550\" height=\"350\"></li>\r\n");
      out.write("\t\t\t\t\t\t      ");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t      </ul>\r\n");
      out.write("\t\t\t\t\t\t      <div id=\"next");
      out.print( i );
      out.write("\" class=\"slideBtn\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/image/오른쪽 화살표.png\" alt=\"\" width=\"50\"></div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>");
      out.print( p.getPostContent() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"explain\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"petlife\">");
      out.print( category );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"expansionbox\">카테고리</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
 for(int a=0;a<=mpList.size();a++){ 
								if(a==mpList.size()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"expansionbox");
      out.print( i );
      out.write("\" class=\"expansionbox\">관심글 등록</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
	break;
								}
								MarkPost mp = mpList.get(a);
								if(mp.getPostNum() == p.getPostNum()) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"expansionbox");
      out.print( i );
      out.write("\" class=\"expansionbox\">관심글 취소</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
	break;
								} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"likeBtn");
      out.print( i );
      out.write("\" class=\"expansionbox\">");
      out.print( p.getPostLike() );
      out.write(" like</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"comment");
      out.print( i );
      out.write("\"class=\"comment\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment0\">댓글</div>\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(!pclist.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 for(int x=0;x<pclist.size();x++){ 
									PostComment pc = pclist.get(x);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(p.getPostNum() == pc.getPostNum()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"comment2-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(!proList.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 for(int o=0;o<=proList.size();o++) {
											if(o==proList.size()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"comment2-1img\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 break;
											}
											Media cProimg = proList.get(o);
											if(cProimg.getMemberId().equals(pc.getMemberid())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"comment2-1img\" src=\"");
      out.print( request.getContextPath() );
      out.write("/uploadFiles/");
      out.print( cProimg.getWebName() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 break;
											} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"comment2-1img\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"comment2-3\">");
      out.print( pc.getMemberid() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"comment2-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(pc.getcRange() == 2){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(loginUser.getNickname().equals(pc.getMemberid())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( pc.getcContent() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t비밀 댓글 입니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print( pc.getcContent() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"comment2-4");
      out.print( x );
      out.write("\" class=\"comment2-4\">");
      out.print( pc.getcLike() );
      out.write(" like</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"comment2-5");
      out.print( x );
      out.write("\" class=\"comment2-5\">답글달기</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(pc.getMemberid().equals(loginUser.getNickname())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"comment2-6");
      out.print( x );
      out.write("\" class=\"comment2-6\">삭제</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   /*  댓글좋아요수! */\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar cmlikeBtn = \"#comment2-4\"+");
      out.print( x );
      out.write(";\r\n");
      out.write("\t\tvar cNum = ");
      out.print( pc.getcNum() );
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(cmlikeBtn).click(function(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: 'commentlike.up',\r\n");
      out.write("\t\t\t\tdata: {cNum:cNum},\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t$(cmlikeBtn).text(data+\" like\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 댓글에 답글달기 버튼나오게하기 */\r\n");
      out.write("\t\tvar ansBtn = \"#comment2-5\"+");
      out.print( x );
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(ansBtn).click(function(){\r\n");
      out.write("\t\t\tvar ansdiv = \"#commentansdiv\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\t\tvar anstext = \"#commentanstext\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\t\tvar ansget = \"----- ");
      out.print( pc.getMemberid() );
      out.write(" 님에게 답글달기 -----\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tansbull = false;\r\n");
      out.write("\t\t\t$(ansdiv).show();\r\n");
      out.write("\t\t\t$(anstext).text(ansget);\r\n");
      out.write("\t\t\tcNumber = \"");
      out.print( pc.getcNum() );
      out.write("\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* --------답글버튼 없애기 ------------ */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar ansdiv = \"#commentansdiv\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.commentansclose').click(function(){\r\n");
      out.write("\t\t\t$(ansdiv).hide();\r\n");
      out.write("\t\t\tansbull = true;\r\n");
      out.write("\t\t\tcNumber = \"\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* ---------댓글 삭제하기 -------------- */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar cmDeleteBtn = \"#comment2-6\"+");
      out.print( x );
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(cmDeleteBtn).click(function(){\r\n");
      out.write("\t\t\tvar result = confirm(\"댓글을 삭제하시겠습니까?\");\r\n");
      out.write("\t\t\tvar cNum = ");
      out.print( pc.getcNum() );
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(result){\r\n");
      out.write("\t\t\t\talert(\"삭제하였습니다.\");\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: 'deleteComment.tl',\r\n");
      out.write("\t\t\t\t\tdata: {cNum:cNum},\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\talert(\"삭제 취소\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(!calist.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 for(int y=0;y<calist.size();y++){
										CAns ca = calist.get(y); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(pc.getcNum() == ca.getcNum()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commentans\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"commentans2-0\">ㄴ</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"commentans2-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(!proList.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 for(int o=0;o<=proList.size();o++) {
											if(o==proList.size()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"commentans2-1img\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 break;
											}
											Media cProimg = proList.get(o);
											if(cProimg.getMemberId().equals(ca.getMemberid())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"commentans2-1img\" src=\"");
      out.print( request.getContextPath() );
      out.write("/uploadFiles/");
      out.print( cProimg.getWebName() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 break;
											} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"commentans2-1img\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"commentans2-3\">");
      out.print( ca.getMemberid() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"\" class=\"commentans2-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(pc.getcRange() == 2){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 if(loginUser.getNickname().equals(pc.getMemberid())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print( ca.getAnsContent() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t비밀 답글 입니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( ca.getAnsContent() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(ca.getMemberid().equals(loginUser.getNickname())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"commentans2-4");
      out.print( y );
      out.write("\"class=\"commentans2-4\">삭제</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t/* ---------답글 삭제하기 -------------- */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar cmDeleteBtn = \"#commentans2-4\"+");
      out.print( y );
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(cmDeleteBtn).click(function(){\r\n");
      out.write("\t\t\tvar result = confirm(\"답글을 삭제하시겠습니까?\");\r\n");
      out.write("\t\t\tvar ansNum = ");
      out.print( ca.getAnsNum() );
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(result){\r\n");
      out.write("\t\t\t\talert(\"삭제하였습니다.\");\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: 'deleteCAns.tl',\r\n");
      out.write("\t\t\t\t\tdata: {ansNum:ansNum},\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\talert(\"삭제 취소\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"commentansdiv");
      out.print( i );
      out.write("\" class=commentansdiv>\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"commentanstext");
      out.print( i );
      out.write("\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"commentansclose\">x</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"commenttextdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"writercomment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"commentrange");
      out.print( i );
      out.write("\" class=\"commentrange\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">전체공개</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">작성자만</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"commenttext");
      out.print( i );
      out.write("\" class=\"commenttext\" type=\"text\" placeholder=\"내용을 입력해주세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"commentsubmit");
      out.print( i );
      out.write("\"class=\"commentsubmit\">댓글달기</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t/* -------- 관심글 등록 -----------*/\r\n");
      out.write("\t\tvar markPostBtn = \"#expansionbox\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\t$(markPostBtn).click(function(){\r\n");
      out.write("\t\t\tvar postNum = ");
      out.print( p.getPostNum() );
      out.write(";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: 'insertMarkPost.tl',\r\n");
      out.write("\t\t\t\tdata: {postNum:postNum},\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* ---------- 게시글 삭제하기 ------------ */\r\n");
      out.write("\t\tvar deleteBtn = \"#cDelete\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(deleteBtn).click(function(){\r\n");
      out.write("\t\t\tvar result = confirm(\"게시글을 삭제하시겠습니까?\");\r\n");
      out.write("\t\t\tvar pNum = ");
      out.print( p.getPostNum() );
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(result){\r\n");
      out.write("\t\t\t\talert(\"삭제하였습니다.\");\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: 'deletePost.tl',\r\n");
      out.write("\t\t\t\t\tdata: {pNum:pNum},\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\talert(\"삭제 취소\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* ------------댓글 입력하기 ------------- */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar commentsubmit = \"#commentsubmit\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\tvar commenttextch = \"#commenttext\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$(commenttextch).keydown(function(key){\r\n");
      out.write("\t\t\t\tvar $commenttextcm = $(commenttextch).val();\r\n");
      out.write("\t\t\t\tif($commenttextcm != \"\"){\r\n");
      out.write("\t\t\t\t\tansempty = true;\r\n");
      out.write("\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\tansempty = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(key.keyCode == 13){\r\n");
      out.write("\t\t\t\t\tvar commenttext = \"#commenttext\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\t\t\t\tvar writer = '");
      out.print( loginUser.getMemberId() );
      out.write("';\r\n");
      out.write("\t\t\t\t\tvar content = $(commenttext).val();\r\n");
      out.write("\t\t\t\t\tvar pNum = ");
      out.print( p.getPostNum() );
      out.write(";\r\n");
      out.write("\t\t\t\t\tvar $range = \"#commentrange\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\t\t\t\tvar range = $($range).val();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(ansempty && ansbull){\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl: 'insertComment.tl',\r\n");
      out.write("\t\t\t\t\t\t\tdata: {writer:writer, pNum:pNum, content:content, range:range},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t} else if(ansempty && !ansbull){\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl: 'insertCAns.tl',\r\n");
      out.write("\t\t\t\t\t\t\tdata: {cNumber:cNumber, writer:writer, content:content},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(commentsubmit).click(function(){\r\n");
      out.write("\t\t\t\tvar $commenttextcm = $(commenttextch).val();\r\n");
      out.write("\t\t\t\tif($commenttextcm != \"\"){\r\n");
      out.write("\t\t\t\t\tansempty = true;\r\n");
      out.write("\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\tansempty = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar commenttext = \"#commenttext\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\t\t\tvar writer = '");
      out.print( loginUser.getMemberId() );
      out.write("';\r\n");
      out.write("\t\t\t\tvar content = $(commenttext).val();\r\n");
      out.write("\t\t\t\tvar pNum = ");
      out.print( p.getPostNum() );
      out.write(";\r\n");
      out.write("\t\t\t\tvar $range = \"#commentrange\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\t\t\t\tvar range = $($range).val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(ansempty && ansbull){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl: 'insertComment.tl',\r\n");
      out.write("\t\t\t\t\t\tdata: {writer:writer, pNum:pNum, content:content, range:range},\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t} else if(ansempty && !ansbull){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl: 'insertCAns.tl',\r\n");
      out.write("\t\t\t\t\t\tdata: {cNumber:cNumber, writer:writer, content:content},\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("/* ------------좋아요 올리기 ---------------- */\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    \tvar likeBtn = \"#likeBtn\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("    \tvar postNum = ");
      out.print( p.getPostNum() );
      out.write(";\r\n");
      out.write("    \t$(likeBtn).click(function(){\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("    \t\t\turl: 'postlike.up',\r\n");
      out.write("    \t\t\tdata: {postNum:postNum},\r\n");
      out.write("    \t\t\tsuccess: function(data){\r\n");
      out.write("    \t\t\t\t$(likeBtn).text(data+\" like\");\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("/* -------------이미지 슬라이드-------------------------- */\r\n");
      out.write("      var imgs;\r\n");
      out.write("      var img_count;\r\n");
      out.write("      var img_position = 1;\r\n");
      out.write("      var slide = \"#slide\"+");
      out.print( i );
      out.write("+\" ul\";\r\n");
      out.write("      var backbtn = \"#back\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("      var nextbtn = \"#next\"+");
      out.print( i );
      out.write(";\r\n");
      out.write("\r\n");
      out.write("      imgs = $(slide);\r\n");
      out.write("      $back = $(backbtn);\r\n");
      out.write("      $next = $(nextbtn);\r\n");
      out.write("      img_count = imgs.children().length;\r\n");
      out.write("\r\n");
      out.write("      //버튼을 클릭했을 때 함수 실행\r\n");
      out.write("      $back.click(function () {\r\n");
      out.write("        back();\r\n");
      out.write("      });\r\n");
      out.write("      $next.click(function () {\r\n");
      out.write("        next();\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      function back() {\r\n");
      out.write("        if(1<img_position){\r\n");
      out.write("          imgs.animate({\r\n");
      out.write("            left:'+=550px'\r\n");
      out.write("          });\r\n");
      out.write("          img_position--;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("      function next() {\r\n");
      out.write("        if(img_count>img_position){\r\n");
      out.write("          imgs.animate({\r\n");
      out.write("            left:'-=550px'\r\n");
      out.write("          });\r\n");
      out.write("          img_position++;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('.slideBtn').hover(function(){\r\n");
      out.write("\t\t\t$('.slideBtn').css(\"opacity\", \"1\");\r\n");
      out.write("\t\t}, function(){\r\n");
      out.write("\t\t\t$('.slideBtn').css(\"opacity\", \"0\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* ----------------무한스크롤------------ */\r\n");
      out.write("\t\tstop = true;\r\n");
      out.write("\t\tif(1500 > $('.sectiondiv').height()){\r\n");
      out.write("\t\t\tstop = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(window).scroll(function(){\r\n");
      out.write("\t\t\tif(stop &&$(window).scrollTop() == $(document).height() - $(window).height() && ($('section').css(\"height\") < $('.sectiondiv').css(\"height\"))){\r\n");
      out.write("\t\t\t\t$('section').css(\"height\", \"+=500px\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<footer>제작사:hoseong</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
