/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-22 12:52:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/main/main.jsp", Long.valueOf(1587559908509L));
    _jspx_dependants.put("/views/main/alertchat.jsp", Long.valueOf(1587041088000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>ULTARY</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');

	Member loginUser = (Member)session.getAttribute("loginUser");
	String msg = (String)request.getAttribute("msg");
	String absroute = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메인화면</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/main.css\">\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\"  href=\"https://han3283.cafe24.com/js/lightslider/css/lightslider.css\"/>\r\n");
      out.write("\t<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://han3283.cafe24.com/js/lightslider/js/lightslider.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/alertchatMain.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"alert\">\r\n");
      out.write("\t\t<div id=\"alerttitle\">전체알림</div>\r\n");
      out.write("\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"alertspace\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('.alert').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('.alert').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('.alert').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#alertbuttondiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t<div id=\"chatdiv\">\r\n");
      out.write("\t\t<div id=\"chatdivleft\">\r\n");
      out.write("\t\t\t<div id=\"chatdivleft1\">\r\n");
      out.write("\t\t\t\t<img id=\"individualtalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/갠톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"chatdivleft2\">\r\n");
      out.write("\t\t\t\t<img id=\"grouptalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/단체톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"chatdivright\">\r\n");
      out.write("\t\t\t<div id=\"chattitle\">울타리 톡</div>\r\n");
      out.write("\t\t\t<div id=\"chatsearch\">\r\n");
      out.write("\t\t\t\t<div id=\"chatsearchdiv\">\r\n");
      out.write("\t\t\t\t\t<img id=\"chatsearchimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/검색.png\">\r\n");
      out.write("\t\t\t\t\t<input id=\"chatsearchtext\" type=\"search\" placeholder=\"검색할 회원이나 채팅방을 입력해주세요.\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('#chatdiv').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('#chatdiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('#chatdiv').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#chatbtn').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div id=\"expansion\">\r\n");
      out.write("\t\t<div id=\"expansionIn\">\r\n");
      out.write("\t\t\t<div id=\"expansiontop\">\r\n");
      out.write("\t\t\t\t<div id=\"expansionL\">\r\n");
      out.write("\t\t\t\t\t<img id=\"mainimg\"src=\"");
      out.print( request.getContextPath() );
      out.write("/image/1.png\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"expansionR\">\r\n");
      out.write("\t\t\t\t\t<div id=\"expansionexit\">X</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"expansionRheader\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"expansionWriter\">\r\n");
      out.write("\t\t\t\t\t\t\t<img id=\"expansionimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"expansionWri\">닉네임</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"expansiondate\">게시일 | 2020. 03. 29 (SUN) 17:55</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"expansionRsection\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"expansionTitle\">Title | 제목<hr></div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"expansioncontent\">\r\n");
      out.write("\t\t\t\t\t\t\t내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용\r\n");
      out.write("\t\t\t\t\t\t\t내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용\r\n");
      out.write("\t\t\t\t\t\t\t내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"expansioncomment\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment\">댓글</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commentans\">답글</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commentans\">답글</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commentans\">답글</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commentans\">답글</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment\">댓글</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment\">댓글</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment\">댓글</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment\">댓글</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment\">댓글</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment\">댓글</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment\">댓글</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"comment\">댓글</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"expansionbottom\">\r\n");
      out.write("\t\t\t\t<div class=\"expansionbox\">카테고리</div>\r\n");
      out.write("\t\t\t\t<div id=\"petlife\">펫 일상</div>\r\n");
      out.write("\t\t\t\t<div class=\"expansionbox\">관심글 등록</div>\r\n");
      out.write("\t\t\t\t<div id=\"like\">♡</div>\r\n");
      out.write("\t\t\t\t<div class=\"expansionbox\">222 like</div>\r\n");
      out.write("\t\t\t\t<img id=\"likeimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/좋아요.png\">\r\n");
      out.write("\t\t\t\t<div id=\"commenttextdiv\">\r\n");
      out.write("\t\t\t\t\t<input id=\"commenttext\" type=\"text\" placeholder=\"내용을 입력해주세요\">\r\n");
      out.write("\t\t\t\t\t<input id=\"commentsubmit\" type=\"submit\" value=\"댓글달기\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('#expansion').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('#expansion').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#expansion').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('#expansion').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('.exBtn').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#expansion').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"top-header\">\r\n");
      out.write("\t\t\t<div id=\"top-left\">\r\n");
      out.write("\t\t\t\t");
 if((loginUser) != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"top-button\" id=\"chatbtn\">\r\n");
      out.write("\t\t\t\t\t<img class=\"top-buttonimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/메신저.png\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"top-button\" id=\"alertbuttondiv\">\r\n");
      out.write("\t\t\t\t\t<img class=\"top-buttonimg\" id=\"alertbutton\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/알림.png\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"top-right\">\r\n");
      out.write("\t\t\t\t");
 if((loginUser) == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<button class=\"top-right\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/views/main/ultaryLoginMain.jsp'\">로그인</button>\r\n");
      out.write("\t\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"member\">");
      out.print( loginUser.getNickname() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t<div id=\"nim\">님</div>\r\n");
      out.write("\t\t\t\t<button class=\"top-right\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me?page=main'\">로그아웃</button>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"bottom-header\">\r\n");
      out.write("\t\t\t<div id=\"bottom-header-wrap\">\r\n");
      out.write("\t\t\t\t<div id=\"logeleft1\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"logoleft2\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print( request.getContextPath() );
      out.write("/views/main/main.jsp'><img id=\"logoimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/logo.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"category\">\r\n");
      out.write("\t\t\t<div id='cssmenu'>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a>내울타리</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"menu1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a>타임라인</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a>게시글작성</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a>관심회원</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a>게시글 즐겨찾기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a>내 위탁환경</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a>커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"menu2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a>공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a>모아보기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a>펫일상</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a>펫지식</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a>펫리뷰</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a>펫분양</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href='#'>위탁매칭</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"menu3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>위탁검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>의뢰 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>내가 남긴 리뷰</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href='#'>마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"menu4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='");
      out.print( request.getContextPath() );
      out.write("/views/myPage/memberUpdate.jsp'>내 정보 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='");
      out.print( request.getContextPath() );
      out.write("/views/myPage/pwdUpdate.jsp'>비밀번호변경</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='");
      out.print( request.getContextPath() );
      out.write("/views/myPage/memberDelete.jsp'>회원 탈퇴</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href='#'>고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"menu5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>공지 사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>자주하는 질문</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>1:1 문의</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("<script>\r\n");
      out.write("\t");
 if((loginUser) == null){ 
      out.write("\r\n");
      out.write("\t$('#cssmenu>ul a').click(function(){\r\n");
      out.write("\t\twindow.alert('로그인을 해주세요.');\r\n");
      out.write("\t});\r\n");
      out.write("\t");
 } else{ 
      out.write("\r\n");
      out.write("\t$('#cssmenu>ul>li:eq(0)>a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/post.tl\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu1>li:eq(0) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/post.tl\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu1>li:eq(1) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myUltary/postWrite.jsp\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu1>li:eq(2) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/markmember.mem\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu1>li:eq(3) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/markpost.tl\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu1>li:eq(4) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myUltary/trustEvm.jsp\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#cssmenu>ul>li:eq(1)>a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu2>li:eq(0) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/cmList.po?cnum=1\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu2>li:eq(1) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu2>li:eq(2) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/cmList.po?cnum=2\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu2>li:eq(3) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/cmList.po?cnum=3\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu2>li:eq(4) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/cmList.po?cnum=4\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu2>li:eq(5) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/cmList.po?cnum=5\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#cssmenu>ul>li:eq(2)>a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/views/trustMatch/matching01.jsp\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu3>li:eq(0) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/views/trustMatch/matching01.jsp\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu3>li:eq(1) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/TpostView.tu\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu3>li:eq(2) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/myreview.tu\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#cssmenu>ul>li:eq(3)>a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myPage/memberUpdate.jsp\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu4>li:eq(0) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myPage/memberUpdate.jsp\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu4>li:eq(1) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myPage/pwdUpdate.jsp\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu4>li:eq(2) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/views/myPage/memberDelete.jsp\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#cssmenu>ul>li:eq(4)>a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/slist.no'\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu5>li:eq(0) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/slist.no\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu5>li:eq(1) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/faq.sv\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu5>li:eq(2) a').click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/views/support/InquirySend.jsp\";\r\n");
      out.write("\t});\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div id=\"mainleft\">\r\n");
      out.write("\t\t\t<img class=\"arrow\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/왼쪽 화살표.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"mainright\">\r\n");
      out.write("\t\t\t<img class=\"arrow\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/오른쪽 화살표.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"main\">\r\n");
      out.write("\t\t\t<ul id=\"slider\" class=\"slider\">\r\n");
      out.write("                <li class=\"item1\">\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item2\">\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item3\">\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item4\">\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item5\">\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item6\">\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("   \t\t$(\"#slider\").lightSlider({\r\n");
      out.write("\t\t\tmode:'slide',    // 이미지가 표시되는 형식 (fade / slide)\r\n");
      out.write("   \t     \tloop:true,       // 무한반복 할 것인지\r\n");
      out.write("   \t    \tauto:true,       // 자동 슬라이드\r\n");
      out.write("   \t     \tkeyPress:true,   // 키보드 탐색 허용\r\n");
      out.write("   \t     \tpager:false,     // 페이지 표시\r\n");
      out.write("   \t     \tspeed:1500,      // 슬라이드 되는 속도\r\n");
      out.write("   \t     \tpause:3000       // 이미지가 머무는 시간\r\n");
      out.write("   \t \t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<form onsubmit=\"return search();\" action=\"");
      out.print( request.getContextPath() );
      out.write("/search.mem\">\r\n");
      out.write("\t\t<div id=\"search\">\r\n");
      out.write("\t\t\t<div id=\"search-wrap\">\r\n");
      out.write("\t\t\t\t<div id=\"search-left\"></div>\r\n");
      out.write("\t\t\t\t<select id=\"searchselect\" name=\"searchselect\">\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">회원</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">게시글</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<input id=\"searchtext\" name=\"searchtext\" type=\"search\" placeholder=\"검색\">\r\n");
      out.write("\t\t\t\t<input id=\"searchbutton\" type=\"submit\" value=\"검색\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction search(){\r\n");
      out.write("\t\t");
 if((loginUser) == null){ 
      out.write("\r\n");
      out.write("\t\talert('로그인을 해주세요.');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\tif($('#searchtext').val() == \"\"){\r\n");
      out.write("\t\t\t\talert('검색어를 입력해주세요');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<article>\r\n");
      out.write("\t\t<div id=\"articlewrap\">\r\n");
      out.write("\t\t\t<div id=\"article1\" class=\"article\">\r\n");
      out.write("\t\t\t\t<div class=\"articleTitle\">공지사항</div>\r\n");
      out.write("\t\t\t\t<div class=\"articlecontent\">\r\n");
      out.write("\t\t\t\t\t<div class=\"articleinner\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"article2\" class=\"article\">\r\n");
      out.write("\t\t\t\t<div class=\"articleTitle\">최신글</div>\r\n");
      out.write("\t\t\t\t<div class=\"articlecontent\">\r\n");
      out.write("\t\t\t\t\t<div class=\"articleinner\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"article3\" class=\"article\">\r\n");
      out.write("\t\t\t\t<div class=\"articleTitle\">인기글</div>\r\n");
      out.write("\t\t\t\t<div class=\"articlecontent\">\r\n");
      out.write("\t\t\t\t\t<div class=\"articleinner\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"article4\" class=\"article\">\r\n");
      out.write("\t\t\t\t<div class=\"articleTitle\">반려동물 행사</div>\r\n");
      out.write("\t\t\t\t<div class=\"articlecontent\">\r\n");
      out.write("\t\t\t\t\t<div class=\"articleinner\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>게시글 제목</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</article>\r\n");
      out.write("\t<footer>제작 : 한호성</footer>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
