/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-23 19:36:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.trustMatch;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import java.util.ArrayList;
import trust.model.vo.*;
import member.model.vo.Member;

public final class matching04_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/tr_nav.jsp", Long.valueOf(1587041088000L));
    _jspx_dependants.put("/views/common/tr_aside.jsp", Long.valueOf(1587558273973L));
    _jspx_dependants.put("/views/common/commonheader.jsp", Long.valueOf(1587041194000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("trust.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Member m = (Member)request.getAttribute("m");
	ArrayList<Member> mark = (ArrayList<Member>)request.getAttribute("mark");
	ArrayList<TrustReview> trList = (ArrayList<TrustReview>)request.getAttribute("trList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>커뮤니티용</title>\r\n");
      out.write("</head>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/common/완성본틀.css\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-latest.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/trust/matching04.css\">\r\n");
      out.write("\t<style>\r\n");
      out.write("\r\n");
      out.write("#map_div{\r\n");
      out.write("\twidth: 803px;\r\n");
      out.write("\theight : 167px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground: whitesmoke;\r\n");
      out.write("}\r\n");
      out.write("/* #map{\r\n");
      out.write("\twidth:600px;\r\n");
      out.write("\theight:350px;\r\n");
      out.write("\tborder: 4px solid skyblue;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tmargin-left: 30px;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("#map_content{\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("#keyword{\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("}\r\n");
      out.write("#subBTn{\r\n");
      out.write("\tbackground: skyblue;\r\n");
      out.write("\tcolor : white;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>    \r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"all\">\r\n");
      out.write("\t\t<div id=\"all-wrap\">\r\n");
      out.write("\t\t\t");
      out.write('\r');
      out.write('\n');
 
	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header틀</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/common/commonheader.css\">\r\n");
      out.write("     <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"chatdiv\">\r\n");
      out.write("\t\t<div id=\"chatdivleft\">\r\n");
      out.write("\t\t\t<div id=\"chatdivleft1\">\r\n");
      out.write("\t\t\t\t<img id=\"individualtalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/갠톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"chatdivleft2\">\r\n");
      out.write("\t\t\t\t<img id=\"grouptalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/단체톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"chatdivright\">\r\n");
      out.write("\t\t\t<div id=\"chattitle\">울타리 톡</div>\r\n");
      out.write("\t\t\t<div id=\"chatsearch\">\r\n");
      out.write("\t\t\t\t<div id=\"chatsearchdiv\">\r\n");
      out.write("\t\t\t\t\t<img id=\"chatsearchimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/검색.png\">\r\n");
      out.write("\t\t\t\t\t<input id=\"chatsearchtext\" type=\"search\" placeholder=\"검색할 회원이나 채팅방을 입력해주세요.\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('#chatdiv').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('#chatdiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('#chatdiv').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#chatbtn').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<div id=\"alert-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"alerttitle\">전체알림</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"alertspace\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('.alert').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('.alert').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('.alert').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#alertbuttondiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t\t<div id=\"header-top\">\r\n");
      out.write("\t\t\t\t\t<div id=\"chatbtn\"><img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/메신저.png\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"alertbuttondiv\"><img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/알림.png\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"header-topR\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"nick\">");
      out.print( loginUser.getNickname() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"nim\">님</div>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"logout\" class=\"top-right\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"header-bottom\">\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print( request.getContextPath() );
      out.write("/views/main/main.jsp'><img id=\"logoimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/logo.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/common/cm_nav.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t\t\t<div id='cssmenu'>\r\n");
      out.write("               <ul>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href='#'>내울타리</a>\r\n");
      out.write("                     <ul id=\"menu1\">\r\n");
      out.write("                        <li><a href='#'>타임라인</a></li>\r\n");
      out.write("                        <li><a href='#'>게시글작성</a></li>\r\n");
      out.write("                        <li><a href='#'>관심회원</a></li>\r\n");
      out.write("                        <li><a href='#'>게시글 즐겨찾기</a></li>\r\n");
      out.write("                        <li><a href='#'>내 위탁환경</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href='");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po'>커뮤니티</a>\r\n");
      out.write("                     <ul id=\"menu2\">\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmnlist.po'>공지사항</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po'>모아보기</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmdlist.po'>펫일상</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmklist.po'>펫지식</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmrlist.po'>펫리뷰</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmrelist.po'>펫분양</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class='active'><a href='#'>위탁매칭</a>\r\n");
      out.write("                     <ul id=\"menu3\">\r\n");
      out.write("                        <li><a href='#'>위탁검색</a></li>\r\n");
      out.write("                        <li><a href='#'>의뢰 관리</a></li>\r\n");
      out.write("                        <li><a href='#'>내가 남긴 리뷰</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a href='#'>마이페이지</a>\r\n");
      out.write("                     <ul id=\"menu4\">\r\n");
      out.write("                        <li><a href='#'>내 정보 관리</a></li>\r\n");
      out.write("                        <li><a href='#'>비밀번호변경</a></li>\r\n");
      out.write("                        <li><a href='#'>회원 탈퇴</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a href='#'>고객센터</a>\r\n");
      out.write("                     <ul id=\"menu5\">\r\n");
      out.write("                        <li><a href='#'>공지 사항</a></li>\r\n");
      out.write("                        <li><a href='#'>자주하는 질문</a></li>\r\n");
      out.write("                        <li><a href='#'>1:1 문의</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"asidesection\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/common/tr_aside.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>z\r\n");
      out.write("\t<aside>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"/Ultary/views/trustMatch/matching01.jsp\">위탁검색</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/TpostView.tu\">의뢰 관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/myreview.tu\">내가 남긴 리뷰</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</aside>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t <div>\r\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/DetailMatch.tu\">\r\n");
      out.write("            <div id=\"matching\">\r\n");
      out.write("\t\t\t<h1 id=\"title\">의뢰관리</h1>\r\n");
      out.write("\t\t\t<p id=\"title-1\">위탁 내용 상세보기와 진행사항을 보여드립니다.</p>\r\n");
      out.write("\t\t\t\t<hr style=\"margin-left:10px;\">\r\n");
      out.write("\t\t\t<br clear=\"all\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div id=\"page\">\r\n");
      out.write("\t\t<div id=\"page1\">\r\n");
      out.write("\t\t\t<img src=\"/Ultary/views/trustMatch/photo.jpg\" id=\"profile\" class=\"profile-photo\">\r\n");
      out.write("\t\t\t<div id=\"page2\">\r\n");
      out.write("\t\t\t<span id=\"name\"><p><b>");
      out.print(m.getNickname() );
      out.write("</b></p></span>\r\n");
      out.write("\t\t\t");
boolean a = false; 
      out.write("\r\n");
      out.write("\t\t\t");
for(int i=0;i<mark.size();i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t");
if(mark.get(i).getMemberId().equals(loginUser.getMemberId())) {
					a = true;
					break;
				} else{
					a=false;
				}
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\t\r\n");
      out.write("\t\t\t");
if(a){ 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"mark\" class=\"infobutton1\">관심회원</div>\r\n");
      out.write("\t\t\t");
} else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"infobutton1\" onclick=\"markmem('");
      out.print(m.getMemberId());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(loginUser.getMemberId());
      out.write(");\">관심등록</div>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t<span id=\"address\"><p><b>");
      out.print(m.getAddress() );
      out.write("</b><p></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\tfunction markmem(nick,memid){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tconsole.log(nick);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: 'markmember.mark',\r\n");
      out.write("\t\t\t\t\tdata: {markmem:nick, memberid:memid},\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\talert('관심등록이 완료되었습니다.');\r\n");
      out.write("\t\t\t\t\t\tlocation.reload(); \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<h5 style=\"text-align:center;\">상세내용</h5>\r\n");
      out.write("\t\t<div id=\"detail\" class=\"detail\">가정집이고요 현재는 펫시팅으로 여행이나 이사가실때 멸절기간(설날,추석 가능)이나 장기보육한 시간이 된지 15년 이상 경력이 되었네요</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h5 style=\"text-align:center;\">돌봄환경</h5>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div class=detail>\r\n");
      out.write("\t\t\t<p>");
      out.print(m.getTrustfield() );
      out.write("</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<h5 style=\"text-align:center;\">거주지역</h5>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div id=\"area\">\r\n");
      out.write("\t\t\t<div id=\"map\" style=\"width: 803px; height: 250px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<div id=\"map\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id =\"map_div\">\r\n");
      out.write("\t\t\t\t<div id =\"map_content\">\r\n");
      out.write("\t\t\t\t\t <form onsubmit=\"searchPlaces(); return false;\"> \r\n");
      out.write("\t\t\t\t\t   <input type=\"text\" id=\"keyword\" value=\"");
      out.print(m.getAddress());
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t   <button type=\"submit\" id='subBTn'>검색하기</button> \r\n");
      out.write("\t\t\t\t\t </form> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=4aaf89e85083d844d407d2aefdb3b6e2&libraries=services\"></script>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 마커를 클릭하면 장소명을 표출할 인포윈도우 입니다\r\n");
      out.write("\t\t\tvar infowindow = new kakao.maps.InfoWindow({zIndex:1});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("\t\t\t    mapOption = {\r\n");
      out.write("\t\t\t        center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표\r\n");
      out.write("\t\t\t        level: 5 // 지도의 확대 레벨\r\n");
      out.write("\t\t\t    };  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 지도를 생성합니다    \r\n");
      out.write("\t\t\tvar map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 장소 검색 객체를 생성합니다\r\n");
      out.write("\t\t\tvar ps = new kakao.maps.services.Places(); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsearchPlaces();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//키워드 검색을 요청하는 함수입니다\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tfunction searchPlaces() {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t var keyword = document.getElementById('keyword').value;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t if (!keyword.replace(/^\\s+|\\s+$/g, '')) {\r\n");
      out.write("\t\t\t\t\t     alert('키워드를 입력해주세요!');\r\n");
      out.write("\t\t\t\t\t     return false;\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t // 장소검색 객체를 통해 키워드로 장소검색을 요청합니다\r\n");
      out.write("\t\t\t\t\t ps.keywordSearch( keyword, placesSearchCB); \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 키워드 검색 완료 시 호출되는 콜백함수 입니다\r\n");
      out.write("\t\t\t\t\tfunction placesSearchCB (data, status, pagination) {\r\n");
      out.write("\t\t\t\t\t    if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t        // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해\r\n");
      out.write("\t\t\t\t\t        // LatLngBounds 객체에 좌표를 추가합니다\r\n");
      out.write("\t\t\t\t\t        var bounds = new kakao.maps.LatLngBounds();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t        for (var i=0; i<data.length; i++) {\r\n");
      out.write("\t\t\t\t\t            displayMarker(data[i]);    \r\n");
      out.write("\t\t\t\t\t            bounds.extend(new kakao.maps.LatLng(data[i].y, data[i].x));\r\n");
      out.write("\t\t\t\t\t        }       \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t        // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다\r\n");
      out.write("\t\t\t\t\t        map.setBounds(bounds);\r\n");
      out.write("\t\t\t\t\t    } \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 지도에 마커를 표시하는 함수입니다\r\n");
      out.write("\t\t\tfunction displayMarker(place) {\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    // 마커를 생성하고 지도에 표시합니다\r\n");
      out.write("\t\t\t    var marker = new kakao.maps.Marker({\r\n");
      out.write("\t\t\t        map: map,\r\n");
      out.write("\t\t\t        position: new kakao.maps.LatLng(place.y, place.x) \r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    // 마커에 클릭이벤트를 등록합니다\r\n");
      out.write("\t\t\t    kakao.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("\t\t\t        // 마커를 클릭하면 장소명이 인포윈도우에 표출됩니다\r\n");
      out.write("\t\t\t        infowindow.setContent('<div style=\"padding:5px;font-size:12px;\">' + place.place_name + '</div>');\r\n");
      out.write("\t\t\t        infowindow.open(map, marker);\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* \r\n");
      out.write("\t\t\t우측 상단에 컨트롤러 추가\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//일반 지도와 스카이뷰로 지도 타입을 전환할 수 있는 지도타입 컨트롤을 생성합니다\r\n");
      out.write("\t\t\tvar mapTypeControl = new kakao.maps.MapTypeControl();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//지도에 컨트롤을 추가해야 지도위에 표시됩니다\r\n");
      out.write("\t\t\t//kakao.maps.ControlPosition은 컨트롤이 표시될 위치를 정의하는데 TOPRIGHT는 오른쪽 위를 의미합니다\r\n");
      out.write("\t\t\tmap.addControl(mapTypeControl, kakao.maps.ControlPosition.TOPRIGHT);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//지도 확대 축소를 제어할 수 있는  줌 컨트롤을 생성합니다\r\n");
      out.write("\t\t\tvar zoomControl = new kakao.maps.ZoomControl();\r\n");
      out.write("\t\t\tmap.addControl(zoomControl, kakao.maps.ControlPosition.RIGHT);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h5 style=\"text-align:center;\">유의사항</h5>\r\n");
      out.write("\t\t<div id=\"area1\">\r\n");
      out.write("\t\t");
 if(m.getTrustAdd() == null) {
      out.write("\r\n");
      out.write("\t\t\t유의 사항이 없습니다.\r\n");
      out.write("\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h5 style=\"text-align:center\">");
      out.print(m.getTrustAdd() );
      out.write("</h5>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<h5 style=\"text-align:center;\">위탁후기</h5>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div id=\"area2\">\r\n");
      out.write("\t\t\t");
if(trList.isEmpty()) {
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"review\">\r\n");
      out.write("\t\t\t\t\t<h4 style=\"text-align:center\">아직 받은 리뷰가 없습니다.</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
} else{ 
      out.write("\r\n");
      out.write("\t\t\t");
for(int i=0;i<trList.size();i++){ 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"review\">\r\n");
      out.write("\t\t\t\t<img src=\"/Ultary/views/trustMatch/photo.jpg\" id=\"profile\" class=\"review-photo\">\r\n");
      out.write("\t\t\t\t<span class=\"point\">\r\n");
      out.write("\t\t\t\t");
for(int j=0;j<trList.get(i).getTrScore();j++){ 
      out.write("\r\n");
      out.write("\t\t\t\t★\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<p class=\"review1\">\r\n");
      out.write("\t\t\t\t");
      out.print(trList.get(i).getTrContent() );
      out.write("\r\n");
      out.write("\t\t\t\t</p>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h5 style=\"text-align:center;cursor: pointer;\">더보기</h5>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"memberid\" name=\"memberid\" value=");
      out.print(m.getMemberId() );
      out.write(">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button id=\"submit\">위탁요청하기</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("         </div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<footer style=\"height:100px\"></footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
