/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-24 11:24:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.trustMatch;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;
import trust.model.vo.*;
import member.model.vo.Member;

public final class postview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/tr_nav.jsp", Long.valueOf(1587041088000L));
    _jspx_dependants.put("/views/common/tr_aside.jsp", Long.valueOf(1587558273973L));
    _jspx_dependants.put("/views/common/commonheader.jsp", Long.valueOf(1587041194000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("trust.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Member m = (Member)request.getAttribute("m");
	Pet pet = (Pet)request.getAttribute("pet");
	TrustPost tp = (TrustPost)request.getAttribute("tp");
	
	String petKind="";
	switch(pet.getPetKind()){
	case '1' : petKind="강아지"; break;
	case '2' : petKind ="고양이"; break;
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>커뮤니티용</title>\r\n");
      out.write("</head>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/common/완성본틀.css\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-latest.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"script.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/trust/matching03.css\">\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"all\">\r\n");
      out.write("\t\t<div id=\"all-wrap\">\r\n");
      out.write("\t\t\t");
      out.write('\r');
      out.write('\n');
 
	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header틀</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/common/commonheader.css\">\r\n");
      out.write("     <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"chatdiv\">\r\n");
      out.write("\t\t<div id=\"chatdivleft\">\r\n");
      out.write("\t\t\t<div id=\"chatdivleft1\">\r\n");
      out.write("\t\t\t\t<img id=\"individualtalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/갠톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"chatdivleft2\">\r\n");
      out.write("\t\t\t\t<img id=\"grouptalk\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/단체톡.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"chatdivright\">\r\n");
      out.write("\t\t\t<div id=\"chattitle\">울타리 톡</div>\r\n");
      out.write("\t\t\t<div id=\"chatsearch\">\r\n");
      out.write("\t\t\t\t<div id=\"chatsearchdiv\">\r\n");
      out.write("\t\t\t\t\t<img id=\"chatsearchimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/검색.png\">\r\n");
      out.write("\t\t\t\t\t<input id=\"chatsearchtext\" type=\"search\" placeholder=\"검색할 회원이나 채팅방을 입력해주세요.\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"chatcontent\">\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentprofile\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofileimg\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"chatcontentimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/프로필.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentprofilename\">\r\n");
      out.write("\t\t\t\t\t\t닉네임\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chatcontentright\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent1\">대화내용1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent2\">대화내용2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontent3\">대화내용3</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chatcontentrightR\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentnum\">5</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"chatcontentfix\">☆</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('#chatdiv').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('#chatdiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('#chatdiv').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#chatbtn').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('#chatdiv').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<div id=\"alert-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"alerttitle\">전체알림</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alertcontentdiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertcontent\">한호성님의 위탁요청이 전송되었습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alertclose\">&nbsp;&nbsp;X</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"alertspace\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"body\").click(function(e){\r\n");
      out.write("\t\tif($('.alert').css('display') == 'block'){\r\n");
      out.write("\t\t\tif(!$('.alert').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if($('.alert').css('display') == 'none'){\r\n");
      out.write("\t\t\tif($('#alertbuttondiv').has(e.target).length) {\r\n");
      out.write("\t\t\t\t$('.alert').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t\t<div id=\"header-top\">\r\n");
      out.write("\t\t\t\t\t<div id=\"chatbtn\"><img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/메신저.png\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"alertbuttondiv\"><img class=\"headerimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/알림.png\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"header-topR\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"nick\">");
      out.print( loginUser.getNickname() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"nim\">님</div>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"logout\" class=\"top-right\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"header-bottom\">\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print( request.getContextPath() );
      out.write("/views/main/main.jsp'><img id=\"logoimg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/image/logo.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/common/cm_nav.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t\t\t<div id='cssmenu'>\r\n");
      out.write("               <ul>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href='#'>내울타리</a>\r\n");
      out.write("                     <ul id=\"menu1\">\r\n");
      out.write("                        <li><a href='#'>타임라인</a></li>\r\n");
      out.write("                        <li><a href='#'>게시글작성</a></li>\r\n");
      out.write("                        <li><a href='#'>관심회원</a></li>\r\n");
      out.write("                        <li><a href='#'>게시글 즐겨찾기</a></li>\r\n");
      out.write("                        <li><a href='#'>내 위탁환경</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href='");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po'>커뮤니티</a>\r\n");
      out.write("                     <ul id=\"menu2\">\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmnlist.po'>공지사항</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmAllList.po'>모아보기</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmdlist.po'>펫일상</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmklist.po'>펫지식</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmrlist.po'>펫리뷰</a></li>\r\n");
      out.write("                        <li><a href='");
      out.print( request.getContextPath() );
      out.write("/cmrelist.po'>펫분양</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class='active'><a href='#'>위탁매칭</a>\r\n");
      out.write("                     <ul id=\"menu3\">\r\n");
      out.write("                        <li><a href='#'>위탁검색</a></li>\r\n");
      out.write("                        <li><a href='#'>의뢰 관리</a></li>\r\n");
      out.write("                        <li><a href='#'>내가 남긴 리뷰</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a href='#'>마이페이지</a>\r\n");
      out.write("                     <ul id=\"menu4\">\r\n");
      out.write("                        <li><a href='#'>내 정보 관리</a></li>\r\n");
      out.write("                        <li><a href='#'>비밀번호변경</a></li>\r\n");
      out.write("                        <li><a href='#'>회원 탈퇴</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a href='#'>고객센터</a>\r\n");
      out.write("                     <ul id=\"menu5\">\r\n");
      out.write("                        <li><a href='#'>공지 사항</a></li>\r\n");
      out.write("                        <li><a href='#'>자주하는 질문</a></li>\r\n");
      out.write("                        <li><a href='#'>1:1 문의</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"asidesection\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/common/tr_aside.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>z\r\n");
      out.write("\t<aside>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"/Ultary/views/trustMatch/matching01.jsp\">위탁검색</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/TpostView.tu\">의뢰 관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/myreview.tu\">내가 남긴 리뷰</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</aside>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/Tpostsend.tu\" onsubmit=\"return datacheck();\">\r\n");
      out.write("            <div id=\"matching\">\r\n");
      out.write("\t\t\t\t<h1 id=\"title\">의뢰관리</h1>\r\n");
      out.write("\t\t\t\t<p id=\"title-1\">위탁 내용 상세보기와 진행사항을 보여드립니다.</p>\r\n");
      out.write("\t\t\t\t\t<hr style=\"margin-left:10px;\">\r\n");
      out.write("\t\t\t\t<br clear=\"all\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"page\">\r\n");
      out.write("\t\t\t\t<div id=\"page1\">\r\n");
      out.write("\t\t\t\t\t<div id=\"page2\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"page2-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/Ultary/views/trustMatch/photo.jpg\" id=\"userphoto\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 id=\"nick1\">");
      out.print(m.getNickname() );
      out.write("<input type=\"hidden\" name = \"memberid\" value=\"");
      out.print(m.getMemberId());
      out.write("\"></h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"page2-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 id=\"pcoment\">님 에게 위탁 요청</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id= \"page3\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"page3-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 style=\"text-align: center;\">반려동물 정보</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"page3-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<table id=\"page3_table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"page3_td\"><div class=\"petname\">반려동물 이름</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>");
      out.print(pet.getPetName() );
      out.write("</label><input type=\"hidden\" name=\"petnum\" value=\"");
      out.print(pet.getPetNum());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"page3_td\"><div class=\"petname\">반려동물 종류</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>");
      out.print(petKind );
      out.write("</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"page3_td\"><div class=\"petname\">성별</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>");
      out.print(pet.getPetGender() );
      out.write("</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"page3_td\"><div class=\"petname\">반려동물 나이</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>");
      out.print(pet.getPetage() );
      out.write("살</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"page3-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/Ultary/views/trustMatch/photo.jpg\" id=\"pet-photo\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"page4\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"page4-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"page4-1-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"page4-1\">거주지역</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan =\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>");
      out.print(m.getAddress() );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"page4-1-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"page4-1\">돌봄기간</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>시작날자</label><input type=\"text\" readonly name=\"startDate\" id=\"startDate\" value=\"");
      out.print(tp.getTrustsDue());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>끝나는 날자</label><input type=\"text\" name=\"endDate\" id=\"endDate\" value=\"");
      out.print(tp.getTrusteDue() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"page4-1-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"page4-1\">위탁방식</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" value=\"");
      out.print(tp.getTrustMeans());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"page4-1-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"page4-1\">비상연락처</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"tel\" id=\"tel\" value=\"");
      out.print(tp.getTrustPhone());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div id=\"page5\">\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"page5-title\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(m.getNickname() );
      out.write(" 님에게 보내는 메세지\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<textarea id=\"page5-textarea\" cols=\"30\" rows=\"30\" name=\"trustAdd\" readonly>");
      out.print(tp.getTrustPS() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" name=\"sub\" id=\"sub\" value=\"요청수정\" onclick=\"location.href=");
      out.print(request.getContextPath());
      out.write("/updateTp.tu?\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" name=\"cancel\" id=\"cancel\" value=\"요청취소\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<footer>from.hoseong</footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
